### ISSUE TITLE
how long does it take?

### ISSUE THREAD

**Issue by joaoavilars** [m4heshd/whatsapp-desktop-dark#10]
![image](https://user-images.githubusercontent.com/42388872/64254834-8f1f9880-cef6-11e9-92b6-4d9835a44622.png)
ERROR: specified service does not exist as installed service

I am installing with the site version of whatsapp as specified in the instructions, but got stuck at this step and does not proceed.

**Comment by KeronCyst** [comment]
I can't translate that, but I had to manually Ctrl+Alt+Del existing WhatsApp.exe instances to get mine to proceed. Maybe you could try that.

**Comment by joaoavilars** [comment]
the translation I put below the picture.
According to the instructions, should the application not be open to perform the installation?

**Comment by joaoavilars** [comment]
and yes, I closed the whatsapp application and ran the installer, it didn't work.

**Comment by m4heshd** [comment]
Hi,
This issue is probably originated from WMIC which means the issue rises from your particular copy of Windows. Can you tell me your Windows build version?

**Comment by joaoavilars** [comment]
The version of windows I am using is:
Windows 10 Pro 1903 - build 18362.295

**Comment by m4heshd** [comment]
Most of the users are on the same version of the platform including me and I've seen many people having issues with WMIC when installing. 

Any chance you can try to install directly from source? Instructions are in the documentation. It'll be great if you can do this because then I'll be able to isolate the issue from generated binary or the environment itself.

**Comment by joaoavilars** [comment]
ok, I'll try and report later.

**Comment by joaoavilars** [comment]
I could find the problem: there was a pending installation on windows. I installed another APP and the installation crashed and I killed.
When I went to install Node he informed me that this installation was pending.
I reinstalled the pending APP and then installed it through WADark.exe and it worked without problems! Thanks a lot for the help!

**Comment by m4heshd** [comment]
That's really good to hear. This issue was really bothering me. Glad you were able to resolve it. Closing the issue.
