### ISSUE TITLE
eACCESS error

### ISSUE THREAD

**Issue by MoerkyMark** [m4heshd/whatsapp-desktop-dark#102]
When running the Script in my Mac I get the following Error: EACCES: permission denied, unlink '/Applications/WhatsApp.app/Contents/Resources/app.asar'

**Comment by eduardodx** [comment]
You probably installed WhatApp from the App Store. This is script apparently does not work with this version. The same problem happened with me and I installed the version from the official site and ran the script again. Everything working now.

**Comment by MoerkyMark** [comment]
Thanks for the tip which almost brought me to success. Meanwhile I upgraded to Catalina and I had to make the WADark file executable first with
`sudo chmod +x WADark`
after that everything works fine.

**Comment by eduardodx** [comment]
Oh, I see. I'm still running High Sierra and I did not need to make it executable. 
Glad to hear it worked for you.

**Comment by m4heshd** [comment]
Closing this since the issue has been solved.
