### ISSUE TITLE
Worked brilliantly until recently

### ISSUE THREAD

**Issue by GBULLR** [m4heshd/whatsapp-desktop-dark#107]
Worked until recently, Now every time I reinstall wadark it goes back to light mode no matter how many times it reverts to light mode

 
![image](https://user-images.githubusercontent.com/16908736/69904705-c4ae1380-1377-11ea-958a-f5c39a69dcd4.png)

**Comment by omar-shukurov** [comment]
Yea it happens to everyone. I guess dev's working on this.

**Comment by GBULLR** [comment]
I have a feeling that kaspersky antivirus is changing reverting the changes from WA dark. I say this because today it blocked my installatio of dark mode mode for chrome so it may be related. 

Just a thought in case someone that really knows what they are doing is looking.

**Comment by m4heshd** [comment]
Can you try the latest release and let us know?

**Comment by m4heshd** [comment]
Closing since the issue is inactive.
