### ISSUE TITLE
MacOS Catalina - Installation Unsucessful

### ISSUE THREAD

**Issue by Miguel-Bento-Github** [m4heshd/whatsapp-desktop-dark#108]
Currently the process is not able to find the app.

```
~~~~ WhatsApp Desktop Dark Mode by m4heshd ~~~~


This process takes at least a minute to complete. So please be patient and let it do the magic..

WhatsApp process not found. Make sure WhatsApp desktop is running before installing dark mode.

Press any key to exit.. 
```

**Comment by m4heshd** [comment]
Please try the latest release and let us know.

**Comment by martaribeiro** [comment]
Hiya!
 I'm having the same prob. I'm running macOS Cataline V10.15.3 and I have followed your steps on how to install it.  After giving premission to WADark, it's labled as TextEdit and if I try to open it with iTerm it opens and closes very fast. It gives me a notification and once it's closed nothing happens to the WhatsApp

What should I be doing?

<img width="588" alt="Screenshot 2020-02-06 at 12 54 00" src="https://user-images.githubusercontent.com/3627336/73938786-e085e680-48df-11ea-9eef-4629db814df8.png">

**Comment by xjeeee** [comment]
how am i supposed to install this? i tried running WADark with iTerm -> it shows exactly the same picture, martaribeiro posted. the text in the red bar reads "broken pipe"

i am running MacOS Catalina on a Late2010 MacBook Air

I'd love to use your software on my Mac as well - on Windows it just works like a charm!

**Comment by m4heshd** [comment]
Closing since the issue seems to be solved.
