### ISSUE TITLE
can't run WADArk on mac

### ISSUE THREAD

**Issue by nesss01** [m4heshd/whatsapp-desktop-dark#109]
i am probably being very stupid, but the WADark file has no extension and opens in TestEdit on my mac. how do i run it?

**Comment by nesss01** [comment]
never mind. found answer below

**Comment by RaymondLWong** [comment]
Please close the issue.

For those who haven't found the answer:

1. open the terminal
`Ctrl + Space`, type `terminal`
2. navigate to the script and unzip
`cd ~/Downloads/ && unzip WADark-0.3.4941-macOS.zip`
3. navigate to unzipped folder
`cd WADark`
4. add execute permissions
`chmod +x WADark`
5. run it
`./WADark`
