### ISSUE TITLE
Error while running `npm install`

### ISSUE THREAD

**Issue by zaloogarcia** [m4heshd/whatsapp-desktop-dark#11]
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by m4heshd** [comment]
Hi @zaloogarcia,
Are you on macOS?

**Comment by zaloogarcia** [comment]
> Hi @zaloogarcia,
> Are you on macOS?

yes! I'm in MacOS

**Comment by m4heshd** [comment]
That was my guess. You have nothing to worry here because that's a module specific to Windows build which handles the application of icon to the windows binary output. You'll have no problem building on mac even though these errors are thrown.
