### ISSUE TITLE
How did you build this?

### ISSUE THREAD

**Issue by dutzi** [m4heshd/whatsapp-desktop-dark#115]
Hey, cool idea! 

I wanted to ask, how did you make this? I mean, what is the workflow? I assume you didn't make a tiny change, save it, reload the entire app and so on... 

Did you work on their web app and then copy the CSS to a file?

I'm asking out of curiosity and because I'm thinking about contributing and was wondering what's the recommended workflow when building such a thing.

Thanks!

**Comment by m4heshd** [comment]
Hi @dutzi,
There's a process that i have created. If you plan to join the development, please introduce yourself on our Telegram chat so i can get you up to date on the debugging process. Closing this thread.
