### ISSUE TITLE
Interface is not as it shown in your thread, colors are mixed up

### ISSUE THREAD

**Issue by fahadsabri** [m4heshd/whatsapp-desktop-dark#116]
![image](https://user-images.githubusercontent.com/46475612/72797940-13c74500-3c53-11ea-91d6-30fbc391a5f5.png)

**Comment by romskidd** [comment]
There has been an update of whatsapp few days ago that make the interface like this, you just need to wait for an update.

**Comment by snorreflorre** [comment]
Duplicate of #114

**Comment by m4heshd** [comment]
Closing this since the issue is a duplicate of #113 and has been fixed in the latest release.
