### ISSUE TITLE
Not working in last Whatsapp Desktop version

### ISSUE THREAD

**Issue by mortenanakin** [m4heshd/whatsapp-desktop-dark#117]

**Comment by ghost** [comment]
Duplicate of #114

**Comment by nzec** [comment]
Doesn't seem to be working at all for me. The script is just stuck at Killling Whatsapp part for over an hour.

**Comment by nathantaal** [comment]
> Doesn't seem to be working at all for me. The script is just stuck at Killling Whatsapp part for over an hour.

I've had that problem, you should retry it a few times

**Comment by OBadstue** [comment]
I have the same problem, have retried over a dozen times, even tried reinstalling whatsapp. Still either stuck at 'killing whatsapp' forever, or just crashes at the same stage

**Comment by ghost** [comment]
@OBadstue try to execute the WADark.exe as admin or kill the whatsapp.exe process with task management.

**Comment by m4heshd** [comment]
Closing this since the issue is a duplicate of #113 and has been fixed in the latest release.
