### ISSUE TITLE
Keeping this project alive (ORIGINALLY: 0.4.315 Bringing Us To An End)

### ISSUE THREAD

**Issue by NCheok** [m4heshd/whatsapp-desktop-dark#121]
With no further updates by Mahesh for 4 months now and with the current CSS script from the other Github focused on the Web Client version through Stylish also broken, it's clear to say that the desktop version of WhatsApp Dark Mode is pretty much at the end?

The current stop gap no longer works, using the latest WhatsApp.dmg and applying the Dark.css simply puts the desktop version into a locked mode continually prompting for updates.

I'm pretty certain that unless Mahesh has the motivation to take this back and bring it back to compatibility state. It has been great when it worked, I personally would have loved to keep seeing this progress but I know it is tough without monetary contributions supporting Mahesh.

**Comment by m4heshd** [comment]
Hi @NCheok,
You've got absolutely nothing to worry. A great new update is right around the corner. Actually It's done. I'm just doing the documentation and final check-ups right now. Current release plan is for this Sunday. I've been updating the progress almost daily on the Telegram chat. Just two more days of bright display agony. Keep in touch. 😊

**Comment by samuthekid** [comment]
can you push the branch? I can give it a test right now :P

**Comment by DaniBedz** [comment]
This is great news! Thanks for keeping us updated @m4heshd - can't wait to try it out.

**Comment by Moulick** [comment]
Man @m4heshd You are the man. Awesome job. Very awesome

**Comment by NCheok** [comment]
@m4heshd I'm very glad to hear you're not letting this awesome project go dormant.

For the rest of the other users, I strongly urge you to buy a few Ko-fi appreciations for @m4heshd, he absolutely deserves it and c'mon, we spend more money on apps, subscriptions, what not.

**Comment by m4heshd** [comment]
@NCheok I hope you're enjoying the latest update. And i really really appreciate the support you've given me in the past and the kind words, the message you're putting out there right now. FYI Your previous contributions actually counted in as a lot of motivation to keep this project alive in such a difficult period of my life. I'll be pinning this thread.

Also thanks @Moulick and @DaniBedz for the compliments.

**Comment by mattish91** [comment]
I just found this project as the bright white strains my eyes due to working alot in front of my computer all day, this is exactly what i needed for whatsapp. Keeps my eyes calm and i really appreciate the time given in to this project for all of us to enjoy! Thank you so much!
