### ISSUE TITLE
Counter on voice notes it's hard to read

### ISSUE THREAD

**Issue by renrique92** [m4heshd/whatsapp-desktop-dark#123]
Can you make it white for better reading?

![image](https://user-images.githubusercontent.com/12242257/73579620-ab9e0d80-4461-11ea-8bd6-79c583580182.png)

**Comment by m4heshd** [comment]
Hi @renrique92,
I can confirm this and It'll be fixed in the next release. Thanks for reporting.

**Comment by m4heshd** [comment]
Fixed in the latest release. Closing.
