### ISSUE TITLE
Saved contact names are grey in group chats

### ISSUE THREAD

**Issue by RuggeDX** [m4heshd/whatsapp-desktop-dark#126]
I'm not sure wether this is intentional or not, but contact names are grey-ish but they used to be colored, just like contacts I haven't saved. Is it possible to tweak this in the css file?

![image](https://user-images.githubusercontent.com/42695100/73592943-1bfb6c00-4500-11ea-8020-f05bebce1858.png)

P.S Thanks m4heshd for the great new update!

**Comment by JackDjTom** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/32743884/73596919-2ed56700-4527-11ea-8317-ccc98854afe1.png)

**Comment by Shuja-Mahmood** [comment]
I found some lead, unfortunately I'm no expert and can't fix it myself.

### dark.css

``` CSS
1007|/* Search result info */
1008|._2ZdUP {
1009|    color: var(--light);
1010|}
```

This code is responsible for the colour change of contact names. Changing it to any other colour also changes the colour of the side panel text to that colour. Removing it completely restores the contact name colours but also makes the most recent messages panel text, black which is difficult to see on a dark background.

**Comment by renrique92** [comment]
Luckily i just read this... i have the same "problem"... it's a silly thing but before, in a group chat, the contacts are colored randomly, any chance to fix this?

![image](https://user-images.githubusercontent.com/12242257/73613474-c349d300-45d4-11ea-9722-ba2e975e5cb3.png)

**Comment by m4heshd** [comment]
Hi. I can reproduce this and It'll be fixed in the next release.

**Comment by m4heshd** [comment]
Fixed in the latest release. Closing.
