### ISSUE TITLE
darkness incomplete

### ISSUE THREAD

**Issue by srihariraj** [m4heshd/whatsapp-desktop-dark#127]
leftside pane (contact list) is always white i could not change it to black
![wadark](https://user-images.githubusercontent.com/52784221/73594278-ea4fc880-4532-11ea-8935-6023762502ff.jpg)

**Comment by Shuja-Mahmood** [comment]
Can you please explain how to replicate the issue?

I'm currently using Windows 10 (1909) and WhatsApp version 0.4.315 and latest (0.4.315) release of WADark and everything seems to work alright.

**Comment by m4heshd** [comment]
You're using an older version of WADark. Please download the latest version in reinstall. Closing the issue.

**Comment by srihariraj** [comment]
I solved it I have a compressed file if u need just extract and work with it
