### ISSUE TITLE
WhatsApp Dark theme doesn't works

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#128]
It gives me this error:
![image](https://user-images.githubusercontent.com/31411531/73595609-ae901100-44e8-11ea-8de9-92713dcfdca2.png)

**Comment by ahanniga** [comment]
Same on MacOS. Versions match. It *did* work before I explored the other themes!

**Comment by m4heshd** [comment]
This issue actually isn't with that particular theme. You must've tried to reinstall a different theme in one go. This is currently a know issue (#122). Current workaround is to restart WADark before reinstalling. So I'm closing this since It's a duplicate.
