### ISSUE TITLE
GUI for update shows v0.3.4941 instead of v0.4.315

### ISSUE THREAD

**Issue by szydyzs** [m4heshd/whatsapp-desktop-dark#129]
FYI...

<img width="572" alt="image" src="https://user-images.githubusercontent.com/60488180/73602117-36ebd180-453c-11ea-92e4-a77003f8baaf.png">

**Comment by RuggeDX** [comment]
What WhatsApp version are you running?

**Comment by m4heshd** [comment]
This issue was in the old binary that was uploaded mistakenly. Please download again. Closing this since there's no issue at the moment.
