### ISSUE TITLE
No background-highlight when @-calling group chat members

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#13]
1. Type "@" in a group chat with multiple people
2. Press Up/Down arrow keys on the keyboard (do not use the mouse) for member selection
3. The background highlight color (of the member's name who will be auto-filled when you press Enter) will be absent

**Comment by Ktklein72** [comment]
Confirmed, I observed the same behavior as stated above on build 4479.

**Comment by m4heshd** [comment]
Yes i can reproduce this issue. This'll be fixed in the next release. Thanks @KeronCyst & @Ktklein72 for reporting.

**Comment by m4heshd** [comment]
This issue is fixed in 783eb39e42166e4f1233c3b4ea0d8496cd2e43fe which took such a huge effort for some specific reasons. But totally worth the trouble. Closing this.
