### ISSUE TITLE
Recording a voice message bug

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#130]
![image](https://user-images.githubusercontent.com/31411531/73619914-75959080-45fd-11ea-9ab4-18c682eb8dc1.png)

as you can see the text (the second counter) is dark too, so it's hard to see. It should be white

**Comment by m4heshd** [comment]
Hi @NicolasPL64,
This is already being tracked on #123. Closing this.
