### ISSUE TITLE
Display GUI using Electron instead of opening browser

### ISSUE THREAD

**Issue by almoghamdani** [m4heshd/whatsapp-desktop-dark#131]
As the title says. It should be pretty straightforward since you are already creating an app like website.

**Comment by m4heshd** [comment]
Hi @almogh52,
The reason i didn't do the GUI with Electron is that it's too big of a dependency to achieve such a simple task. You have no idea how much time i have spent testing every single different GUI framework just to avoid using Electron. I've done so many very successful, way more complicated Electron projects in the past and always got complaints about the weight of the dependency. And the complications it adds when packaging is just not worth the time. Electron is such a good, powerful, well maintained GUI framework but just not for this project. Thanks for your suggestion. Ideas are always appreciated. Closing this.
