### ISSUE TITLE
The "@" Symbol is blacked out when referencing a contact

### ISSUE THREAD

**Issue by JackDjTom** [m4heshd/whatsapp-desktop-dark#132]
As you can see in this picture the @ symbol is blacked out
![image](https://user-images.githubusercontent.com/32743884/73680280-42fe9d00-46bc-11ea-9970-4feddef7dcaf.png)
When i send a message myself the @ symbol has the right color though, like in this picture:
![image](https://user-images.githubusercontent.com/32743884/73680338-590c5d80-46bc-11ea-9c87-c703e795b081.png)

**Comment by m4heshd** [comment]
Ah.. I've actually noticed this on the chat list just when i released but didn't notice these ones. Just confirmed it and It'll be fixed in the next release. Thanks for reporting.

**Comment by m4heshd** [comment]
Fixed in the latest release. Closing.
