### ISSUE TITLE
Feature request: default theme at start

### ISSUE THREAD

**Issue by radu-nh** [m4heshd/whatsapp-desktop-dark#135]
Hi, 

would it be possible to have the option to choose the default theme (light or dark) when WhatsApp opens? 

I use it mostly during the day and would like the dark theme only at night, so it's a bit frustrating to always switch it manually to the light theme.

**Comment by m4heshd** [comment]
There's a button placed on top to switch between color schemes. That's the best i can do at the moment.

UPDATE: I've taken a look and it's highly unlikely this'll be implemented. Closing this for the moment
