### ISSUE TITLE
Add a wrapper around WADark that'll run the required commands when double clicked.

### ISSUE THREAD

**Issue by mrillusi0n** [m4heshd/whatsapp-desktop-dark#136]

**Comment by m4heshd** [comment]
Good idea. We'll keep this in mind for the next release.

**Comment by jaymegordo** [comment]
For anyone else wondering, in terminal:
- `cd ~/Downloads/WADark-mac`
- `chmod +x ./WADark` to mark the file as executable
- `./WADark` to run the file

**Comment by m4heshd** [comment]
Upon research it's come to light that this isn't possible for macOS because the shell script itself will need those permissions to be set manually. So adding it would be redundant. Closing for now.
