### ISSUE TITLE
Few styles broken with Whatsapp version 0.4.930 - MacOS

### ISSUE THREAD

**Issue by kishore-vkrn** [m4heshd/whatsapp-desktop-dark#139]
Reply to a conversion is whited out and blue ticks 
<img width="205" alt="Screenshot 2020-02-19 at 7 27 58 PM" src="https://user-images.githubusercontent.com/13584084/74841362-988aa900-534e-11ea-9c95-8a95bdbc495b.png">

Write / Compose message is  blacked out

<img width="732" alt="Screenshot 2020-02-19 at 7 31 50 PM" src="https://user-images.githubusercontent.com/13584084/74841337-8e68aa80-534e-11ea-9b15-ff31d6889fce.png">

<img width="259" alt="Screenshot 2020-02-19 at 7 28 35 PM" src="https://user-images.githubusercontent.com/13584084/74841399-a5a79800-534e-11ea-938f-0cdcfbd02116.png">

**Comment by UnderEu** [comment]
Can confirm the same issue on my installation after WA 0.4.930 update (macOS)
![Screen Shot 2020-02-19 at 19 43 56](https://user-images.githubusercontent.com/16519758/74887059-97f71000-5358-11ea-8441-d043dc7d6e3b.png)

**Comment by Ktklein72** [comment]
Same exact issue on Windows build too

**Comment by NicolasPL64** [comment]
![image](https://user-images.githubusercontent.com/31411531/74890851-4e57f680-5353-11ea-90e4-acec2645ec43.png)
yep

**Comment by SpeakingColors** [comment]
Same issue as well.

Windows 10 x64, latest windows update done, latest whatsapp desktop. 

Tried to fix it via the overide.json and copying/pasting the code from a working whatsapp desktop version, same issue.

**Comment by JackDjTom** [comment]
@kishorramanan How can u lookup the Whatsapp Desktop version like in your picture ?

**Comment by kishore-vkrn** [comment]
> @kishorramanan How can u lookup the Whatsapp Desktop version like in your picture ?

About Whatsapp

**Comment by ElpadoCan** [comment]
Same issue with Version 0.4.930 on windows 10

**Comment by algotr8der** [comment]
Same occurs on MacOS 10.15.2 (19C57) & WADark v0.4.315.

**Comment by alefranzoni** [comment]
Same from here, I'm on Win10 x64

**Comment by Ktklein72** [comment]
Since the issue appeared a few days back I've been using the 0.4.315 executable (Windows) and for now all is working as it previously was.

**Comment by vatnid** [comment]
Same issue for me. I'm on macOS 10.15.1 and 0.4.315. The emojis also have a light background (as shown in the picture). 
<img width="836" alt="Screenshot 2020-02-23 at 13 59 55" src="https://user-images.githubusercontent.com/37631276/75104536-3f1fc400-5645-11ea-99e8-ac86b726468a.png">

**Comment by Ingenieurs** [comment]
Same Issue here 
Win10 x64 18362.592  
WA Dark 0.4.930

**Comment by anshuman852** [comment]
My whole whatsapp application looks white like totally blank, cant see or touch anything
windows - 4.930 version

**Comment by iambudi** [comment]
On mac dark theme become unusable since i can't see message i type.
I add the style for temporary solution.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/31809529/75210555-fdf9f200-57b3-11ea-8d57-45ecdd1fa18d.png">

Reapplying the dark theme and it works good.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/31809529/75210660-444f5100-57b4-11ea-875c-da14dddd1a84.png">

**Comment by m4heshd** [comment]
Official dark mode is out for WhatsApp desktop. Might change the course of this project. Here's a peek but join the Telegram chat to know more.

![wadarkofficial](https://user-images.githubusercontent.com/6711514/75210785-19f79680-57a8-11ea-9975-7e3c21ed5757.jpg)

**Comment by iambudi** [comment]
Another styling that must be fixed:
1. Blue/Green Tick as read indicator does not work
2. Message Quote is hard to read
3. Emoji list is not transparent

**Comment by iambudi** [comment]
@m4heshd  

> Official dark mode is out for WhatsApp desktop. Might change the course of this project. Here's a peek but join the Telegram chat to know more.

Where can i download the latest one? I check the script update still point to 0.4.315
<img width="466" alt="image" src="https://user-images.githubusercontent.com/31809529/75211039-62698100-57b5-11ea-8cea-e4bf89c86c38.png">

**Comment by iambudi** [comment]
My mistake, you mean officially out from Whatsapp website?

**Comment by m4heshd** [comment]
It's not available to the end user. Enabled it through the source. Still thinking if i should make it available to WADark users. Will decide soon.

**Comment by m4heshd** [comment]
**_UPDATE:_** Official dark mode support is available now from the source build. #147

**Comment by BattouSaeen** [comment]
@m4heshd is it just me or is the official dark theme's text (the text you type for a message) is really dark? For me it's really low contrast, similar to how something disabled looks.

![image](https://user-images.githubusercontent.com/4526700/75436323-3fa7ba00-59b9-11ea-92a0-418936a4f796.png)

**Comment by m4heshd** [comment]
All the mentioned issues are fixed in the latest release. Closing.
