### ISSUE TITLE
Lattest update not working D:

### ISSUE THREAD

**Issue by emiliomtz99** [m4heshd/whatsapp-desktop-dark#142]
I had the previous one, and recently I downloaded the new one, Got stuck in the installation, I've stopped it several times, and started again, I've deleted Whatsapp and reinstalled, and tried different things, nothing worked
 
![Sin título](https://user-images.githubusercontent.com/48834796/74969274-e1d80880-53e1-11ea-86b0-45eb678f7301.png)

**Comment by m4heshd** [comment]
I just tried and it works fine. Can you join the Telegram chat and ask other users to recreate this issue? It might help to narrow it down. Also, try running the installer on a different browser, Preferably Chrome of Firefox.

**Comment by emiliomtz99** [comment]
Worked perfect on Chrome!!! Thanks!
