### ISSUE TITLE
Enabling Official Dark Mode

### ISSUE THREAD

**Issue by firefinchdev** [m4heshd/whatsapp-desktop-dark#147]
@m4heshd Please provide a small guide on how to enable the official dark mode present in WhatsApp latest version.
Also, if possible can we have an option to enable that official theme as an "Theme" in next version of WADark.
Thanks.

**Comment by m4heshd** [comment]
Already added. Try the latest source code. Switch button will now switch between the WADark and official themes.

![image](https://user-images.githubusercontent.com/6711514/75270472-a2198280-5820-11ea-997f-6dd77c440a7d.png)

**Comment by UnderEu** [comment]
Can confirm it's working, based on [822a118](https://github.com/m4heshd/whatsapp-desktop-dark/commit/822a1182d4ea17c63d60d1f721b74908c2016a03) (0.4.930 - macOS)
![Screen Shot 2020-02-25 at 14 14 29](https://user-images.githubusercontent.com/16519758/75273313-63170d00-57df-11ea-9a08-9bd7ad1c7108.png)

**Comment by bthuss-matter** [comment]
cool! thanks @m4heshd !

working well for me on mac

**Comment by firefinchdev** [comment]
Thanks. Its working after the latest commits.

**Comment by m4heshd** [comment]
Implemented in the latest release. Pinning and Closing.

**Comment by iambudi** [comment]
PERFECT! Thanks.
