### ISSUE TITLE
'Colon' is missing after contact name - Group chat in chat list

### ISSUE THREAD

**Issue by UnderEu** [m4heshd/whatsapp-desktop-dark#148]
Regarding 0.4.930 app changes to WADark's 0.4.315 theme

In the chat list, for a group chat, when last received message is someone else's, there's a colon ( : ) after contact name and it's not showing on current theme.

Comparison between WADark's default theme and "official dark theme", below:
![1](https://user-images.githubusercontent.com/16519758/75275488-5f858500-57e3-11ea-89d4-15a092675dba.png)
![2](https://user-images.githubusercontent.com/16519758/75275492-61e7df00-57e3-11ea-82c4-eac3e045f2c2.png)

**Comment by m4heshd** [comment]
Can reproduce. We'll work on this for the next release.

**Comment by m4heshd** [comment]
Fixed in the latest release. Closing.
