### ISSUE TITLE
Improvement suggestion: white "Loading thing" from official dark theme

### ISSUE THREAD

**Issue by UnderEu** [m4heshd/whatsapp-desktop-dark#149]
As you scroll through your chat history, a rounded "Loading thing" appears on top of the chat and vanishes after, well... loading the content. This one, on the recently discovered "official dark theme", is bright. It'd be nice to change its color in order to make even the official theme more consistent - probably (if possibly) official WA devs would realize that at some moment but we can fix it now, you know... 😉

![3](https://user-images.githubusercontent.com/16519758/75285666-cf047000-57f5-11ea-9ab8-1ff7fa38ceab.png)

**Comment by m4heshd** [comment]
I too have noticed this. But i suggest we wait because It'll be gradual updates from now on and they'll definitely fix it in their upcoming build. We don't need to waste more time fixing their issues right? We've done enough free work for them 🤭. Closing for now.
