### ISSUE TITLE
Doesn't show last message written in chat-list

### ISSUE THREAD

**Issue by JackDjTom** [m4heshd/whatsapp-desktop-dark#155]
I don't know if thats a bug from whatsapp or from the darkmode but when i delete the last message written from a chat (delete only for me, not for all) it doesn't show the preview of the message before that in the chatlist.
Example:
in one chat someone writes "Hi" and another one replies with "Hello" then i delete the "Hello" message and it should preview the "Hi" message in the chatlist, but instead it shows nothing there, like in the picture seen:
![image](https://user-images.githubusercontent.com/32743884/75605011-09fcf100-5adf-11ea-8cf2-cccaf59834b0.png)

This bug appears when u restart whatsapp after deleting the message from the chat

**Comment by m4heshd** [comment]
Try the theme switch button to switch the theme to one of the default WhatsApp themes. Then you'll find that It's a bug on WhatsApp's side. Closing this.
