### ISSUE TITLE
Issues with using Terminal to load WADark

### ISSUE THREAD

**Issue by jnt85** [m4heshd/whatsapp-desktop-dark#157]
I tried the method of using Terminal on my mac to execute the command for WADark, but it doesn't seem to work at all.

I entered `chmod +x` and then dragged the file into the terminal, pressed return.

And then `chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...` appeared and then when I dragged the file one more time, it says permission denied.

What should I do?

**Comment by m4heshd** [comment]
You didn't follow the instructions properly. Forget drag and drop. Just open a terminal window exactly where WADark file is located. Then enter `sudo chmod +x WADark`. Now you should be able to run without any issue. Closing this for now.
