### ISSUE TITLE
WADark v0.4.930 macOS installer broken?

### ISSUE THREAD

**Issue by abicelis** [m4heshd/whatsapp-desktop-dark#159]
After downloading the v0.4.930 macOS zip [here](https://github.com/m4heshd/whatsapp-desktop-dark/releases/download/0.4.930/WADark-0.4.930-macOS.zip)
Extracting it and adding execute permission to **WADark** `chmod 744 WADark`

When I launch it, i get this:
<img width="916" alt="Untitled" src="https://user-images.githubusercontent.com/9850854/75695741-8840cb00-5c78-11ea-8bf9-9b996651b5e5.png">

macOS says this about the executable if that helps:
<img width="398" alt="Untitled 2" src="https://user-images.githubusercontent.com/9850854/75695742-8971f800-5c78-11ea-8cd9-cdad6a41c210.png">

This process works for the previous version.
Lemme know if there's something else I can provide.
Also, many thanks for your great work @m4heshd !

**Comment by lukassr** [comment]
Which macOS version are you using?

**Comment by abicelis** [comment]
Catalina. v10.15.3

**Comment by firefinchdev** [comment]
Working fine here on Catalina v10.15.3
1. Downloaded the v0.4.930 macOS zip.
2. Extracted using BetterZip.
3. Run WADark using Finder.

**Comment by abicelis** [comment]
Tried the whole thing again, same deal. 
Used The Unarchiver to extract the **WADark-0.4.930-macOS.zip**, launching **WADark** from Finder without changing any permissions, same thing.

Odd.

**Comment by abicelis** [comment]
Upon further inspection, **WADark-0.4.930-macOS.zip**, as it it downloaded from Firefox, gets an extended attribute added to it called `com.apple.quarantine`, this is supposed to be used by the OS to warn the user and prevent Trojans from stuff that's been downloaded from an app like a browser, or extracted from a file downloaded from an app like a browser.

So naturally, extracting the zip adds that same `com.apple.quarantine` attribute to the extracted files:
```
$ ls -l@
total 100416
-rwxr-xr-x@ 1 abicelis  staff  51401609 28 Feb 02:45 WADark
	com.apple.quarantine	      29
-rwxr-xr-x@ 1 abicelis  staff        28 28 Feb 02:45 info.json
	com.apple.quarantine	      29
-rwxr-xr-x@ 1 abicelis  staff      2801 28 Feb 02:45 override.json
	com.apple.quarantine	      29
drwxr-xr-x@ 3 abicelis  staff        96 28 Feb 02:45 styles
	com.apple.quarantine	      29
```
Removing them with (`xattr -cr ../WADark-macOS/`) allows **WADark** to run fine.

Hope that helps anybody.

**Comment by m4heshd** [comment]
That's a hard one to catch. Glad you managed to solve it.
