### ISSUE TITLE
MacOS: WhatsApp process not found + fix 

### ISSUE THREAD

**Issue by SBerkovic** [m4heshd/whatsapp-desktop-dark#16]
MacOS 10.14.6
Whatsapp Desktop 0.3.4479 - installed from whatsapp.com 
Running from Applications Directory

trying to install the mod I get this error:
`WhatsApp process not found. Make sure WhatsApp desktop is running before installing dark mode`

The fix I found is to add one line of code to [run-darwin.js](https://github.com/m4heshd/whatsapp-desktop-dark/blob/master/run-darwin.js#L37) which changes the psargs from the default value of `lx` to `ax` which will get other users' processes as well as your own. I'm gonna guess that that using `lax` will work fine as well but I did yet not test. 

```
ps.lookup({
        command: execPath,
        psargs: 'ax'
    },
```
I am still not entirely sure why whatsapp is running under a different user

**Comment by m4heshd** [comment]
Hi @SBerkovic,
Thank you for spotting this. I have to acknowledge that this multi-user execution deal going on with *nix systems gets more and more complicated. It can be another user that took ownership of the WhatsApp executable in your environment. But either way this solution is valuable and will be pinned till a release comes out with a permanent fix. 

Anybody who's got the same issue can add `psargs: 'ax'` right after the following line
https://github.com/m4heshd/whatsapp-desktop-dark/blob/5830901483d66df5fcf07a85b2b30047418eed4b/run-darwin.js#L37
