### ISSUE TITLE
MacOS opens Texteditor

### ISSUE THREAD

**Issue by debroervanhenk** [m4heshd/whatsapp-desktop-dark#162]
Hi,

I've downloaded the right version of WhatsApp, downloaded the latest version of your script, but when I open WADark (I'm on Mac) it opens Texteditor... I would love to have dark mode.

Thanks!

**Comment by debroervanhenk** [comment]
Used The Unarchiver to extract the zip and everything works fine!

**Comment by stinkfist93** [comment]
Of course it opens Texteditor, you have to make WADark executable.
After you downloaded it, you have to unzip the folder and then you have
to run the follow two rows of code in the terminal :

cd $HOME/Downloads/WADark-macOS
chmod +x WADark

Finally you now can double click on WADark and surely you will be able to install it
cheers

**Comment by sems** [comment]
Thanks for the solution! @stinkfist93 I was looking for this for a while, now I can read in peace at night :D

**Comment by stinkfist93** [comment]
you are welcome!

**Comment by sems** [comment]
@stinkfist93 Now it is updated in the new readme.md 💛

**Comment by m4heshd** [comment]
Closing this since the issue has been solved.
