### ISSUE TITLE
Doesn't install to russian (cyrillic) Win10

### ISSUE THREAD

**Issue by Sandeant** [m4heshd/whatsapp-desktop-dark#165]
Hi Dear,

I tried install WADark on my PC but it seems that script doesn't work with russian (cyrillic) language windows versions :(
if it’s not difficult for you, could you fix this unpleasant trifle?
![WADark](https://user-images.githubusercontent.com/49731689/76116635-69856000-5ffb-11ea-9933-4f1fc68eeb68.png)

**Comment by m4heshd** [comment]
Hi @Sandeant,
This is a know issue which is a duplicate of #29. You can try solutions from that thread. Add to the same thread if there's any issue. Closing this one.
