### ISSUE TITLE
Message forward info header white

### ISSUE THREAD

**Issue by fcucino** [m4heshd/whatsapp-desktop-dark#17]
After forwarding a message, open the info and look for forward counter. It's white with grey text.

![image](https://user-images.githubusercontent.com/24813315/64426775-c6857500-d0af-11e9-8698-1130112acd39.png)

**Comment by m4heshd** [comment]
Hi @turbostar190,
Can reproduce this issue and will be fixed in the next release. Thanks for reporting. 👍

**Comment by m4heshd** [comment]
Closing this since the issue has been fixed in 19a131940b824c517120b033748ae9b8bab09b18.
