### ISSUE TITLE
I have to reinstall dark mode every few days

### ISSUE THREAD

**Issue by jorgebenaventee** [m4heshd/whatsapp-desktop-dark#171]
So that's it, today I opened Whatsapp and it was in light mode after installing dark mode 2 or 3 days ago.
This happened once last week or so and I had to reinstall it again.

**Comment by m4heshd** [comment]
That's because WhatsApp keeps repeatedly updating their desktop app since recently. What you're experiencing is the expected behavior. Closing this.
