### ISSUE TITLE
Darkmode not complete in Version 0.4.2081

### ISSUE THREAD

**Issue by Redi1973** [m4heshd/whatsapp-desktop-dark#173]
![Whatsapp-Version0 4 2081 ](https://user-images.githubusercontent.com/60320977/77751309-c1751c80-7025-11ea-8ad6-db4573441255.jpg)

**Comment by DominikTV** [comment]
See https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
