### ISSUE TITLE
Deep black theme not displaying correctly on windows 10 

### ISSUE THREAD

**Issue by EggY0lk** [m4heshd/whatsapp-desktop-dark#176]
- WADark ver 0.4.930 
-Whatsapp Web ver 0.4.2081
![2020-03-29 02_59_04-Greenshot](https://user-images.githubusercontent.com/27946481/77831463-52551080-716a-11ea-923e-d804ffa4785b.png)
![2020-03-29 02_58_11-Greenshot](https://user-images.githubusercontent.com/27946481/77831464-53863d80-716a-11ea-8a98-aba0abfaf69a.png)

**Comment by DominikTV** [comment]
Dublicate, see https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

**Comment by EggY0lk** [comment]
> Dublicate, see #172

Ah, thx for the heads up. I tried the workaround and it didnt work for me sadly.
I will just wait till its fixed.

**Comment by UnderEu** [comment]
Duplicate issue, see #172 for further updates.
