### ISSUE TITLE
New style not applied on all parts of the WA window

### ISSUE THREAD

**Issue by TOAOQ** [m4heshd/whatsapp-desktop-dark#177]
When applying any style, the left hand side where all chats are listed is not set with the new colours

![image](https://user-images.githubusercontent.com/40427096/77848097-8a883d80-71c2-11ea-8f6b-831a41253d54.png)

WA version 0.4.2081, macOS version 10.15.3 on a Mac mini script release v0.4.930

**Comment by TOAOQ** [comment]
WA version 0.4.2081, macOS version 10.15.3 on a Mac mini

**Comment by TOAOQ** [comment]
Tried to execute the procedures with SUDO, but no luck :(

Mac-mini:WADark-macOS Q-MacMini$ sudo ./WADark

~~~~ WhatsApp Desktop Dark Mode by m4heshd ~~~~


WADark GUI installer backend started
WADark installer client connected. ID - ****************************
WADark installer client connected. ID - XXXXXXXXXXXXXXXXXX

Theme "Deep Black" was successfully applied.

TIP: You can create/download custom themes using "override.json" (Instructions are in the documentation)

**Comment by Kunal666-cell** [comment]
Facing the same issue. New update broke the whole thing. Throwing it away now

**Comment by chrmey** [comment]
Every update for WA Desktop brakes the styles. But there seems to be a workaround for this one. Check out #172 .

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
