### ISSUE TITLE
Broken theme after Catalina update 10.15.4

### ISSUE THREAD

**Issue by veics** [m4heshd/whatsapp-desktop-dark#178]
After I upgraded Catalina to 10.15.4, the theme seems to be broken. I restored the original theme and then re-applied the dark mode themes, but no luck.
I'm running WADark 0.4.930 + Whatsapp 0.4.2081
![Screen Shot 2020-03-29 at 14 57 25](https://user-images.githubusercontent.com/3967838/77848560-4d29ad00-71ce-11ea-932b-2087fee082b8.png)

![Screen Shot 2020-03-29 at 15 03 27](https://user-images.githubusercontent.com/3967838/77848630-c88b5e80-71ce-11ea-89c0-2a816ad55db8.png)

**Comment by chrmey** [comment]
Known Issue. See #172

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
