### ISSUE TITLE
Option to choose accent color or a way to edit the correct files to do so (user preference color, instead of your default blue)

### ISSUE THREAD

**Issue by UnderEu** [m4heshd/whatsapp-desktop-dark#18]
As the title suggests, it would be nice for the user (myself included) to pick a different color to be the accent one, instead of using the blue one you set this up.

**Comment by m4heshd** [comment]
I was just thinking of adding this feature in the next release. May increase the process weight but still worth the sacrifice. Let's keep this in the work. I'll be posting updates here.

**Comment by m4heshd** [comment]
Hi, Just wanted to let you know that the feature you requested has been added to the source in e66673757f27e0863067563e7de5c2d163a008c3. It'll be great if you can clone the repo and give it a try. Remember It's still not available in binary release.

**Comment by m4heshd** [comment]
I'll be closing the issue since this feature has been added to the latest release. Hope it's what you expected.

**Comment by UnderEu** [comment]
Sorry for being late. I tested the latest update and it kinda works.
Maybe I wasn't clear on my request but my intention was changing the whole window color tint and the app is changing only a few elements, such as notification badge color and grid lines.

To give some exaples...:

Default (#5792ff)
![default](https://user-images.githubusercontent.com/16519758/65437261-e16b1f80-ddf9-11e9-8919-9732fac799ab.png)

Black (#00000)
![000000](https://user-images.githubusercontent.com/16519758/65437274-e4fea680-ddf9-11e9-8790-63e519063670.png)

White (#ffffff)
![ffffff](https://user-images.githubusercontent.com/16519758/65437288-e92ac400-ddf9-11e9-917a-ef68bb585e8b.png)


My intention is having the power to do something like [this](https://userstyles.org/styles/137361/dark-custom-background-whatsapp) (this is the theme I use through Firefox + Stylish addon: 
![Screen Shot 2019-09-23 at 12 03 47](https://user-images.githubusercontent.com/16519758/65437598-7c63f980-ddfa-11e9-88d0-b575bd779556.png)


Oh, and I'm using macOS Mojave (10.14.6) and WhatsApp Desktop (non-Mac App Store version).

**Comment by yurividal** [comment]
@m4heshd you could also add the option to customize the accent color but keep the title bar dark grey. 

i did this by changing the titlebar section to `/* Title bar */
#windows-title-bar {
    background-color: var(--darker) !important; }
#windows-title-minimize:hover, #windows-title-maximize:hover {
    transition: 200ms ease-in-out !important;
    background-color: var(--dark) !important; }
#windows-title-close:hover {
    transition: 200ms ease-in-out !important;
    background-color: #dd3b4f !important; }
`
This allowed me to have my custom accent color in the details, while still not having a huge colorful titlebar.

![image](https://user-images.githubusercontent.com/8555749/65441005-42412a80-ddef-11e9-8229-a1bea5cbb6d2.png)

**Comment by m4heshd** [comment]
@UnderEu, Well the feature request was to change the accent color and since i was also thinking of implementing the same feature i went ahead and added it without complicating the process itself. Too much customization support can make it way too complicated to a beginner level user. But i won't toss the idea aside since it's actually useful. Meanwhile you can use this attached `dark.css` with your script to achieve what you want. Replace the one inside `styles` directory with this one and rerun the script. (Make sure to extract the file first)

[dark.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/3643953/dark.zip)

**Comment by m4heshd** [comment]
Hi @yurividal,
This has been raised before and all those times i recommended users to simply change color values inside the CSS file instead of adding one more step to installation process. I still stand by that decision because as i mentioned in the comment above, It seems to be getting too complicated. I will do more testing and maybe will add a method to override the complete color palette to user's wish.

**Comment by UnderEu** [comment]
> @UnderEu, Well the feature request was to change the accent color and since i was also thinking of implementing the same feature i went ahead and added it without complicating the process itself. Too much customization support can make it way too complicated to a beginner level user. But i won't toss the idea aside since it's actually useful. Meanwhile you can use this attached `dark.css` with your script to achieve what you want. Replace the one inside `styles` directory with this one and rerun the script. (Make sure to extract the file first)
> 
> [dark.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/3643953/dark.zip)

I get it. Too much customization makes the whole process not friendly for beginners but, for the premise your mod exists, I doubt most users will be total beginners. Anyways...
Back to my issue: With my vague programming knowledge, I managed to merge the modified parameters into the 'darwin' CSS and make it work (you sent me a Windows file).
Also, FB released v0.3.4679 update and the mod still works - didn't notice any issue, so far.

![Screen Shot 2019-09-23 at 22 31 47](https://user-images.githubusercontent.com/16519758/65474445-405c8300-de52-11e9-930d-67931c869554.png)
Here's my file: [dark.css.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/3644809/dark.css.zip)

**Comment by m4heshd** [comment]
> you sent me a Windows file

Oops.. My bad. Always Windows biased 😋. 

I agree with you on the fact that this feature is really useful. I'll work on something simpler to perform this task without complicating the installation process.

**Comment by UnderEu** [comment]
> > you sent me a Windows file
> 
> Oops.. My bad. Always Windows biased 😋.
> 
> I agree with you on the fact that this feature is really useful. I'll work on something simpler to perform this task without complicating the installation process.

No rush! As everything works every time WA gets updated, I'm good!
