### ISSUE TITLE
broken for latest verision of whatsapp 0.4.2081 mac

### ISSUE THREAD

**Issue by halpz** [m4heshd/whatsapp-desktop-dark#182]
the injection is not working as intended, there are still white backgrounds in the the latest whatsapp verion

**Comment by anhost** [comment]
Windows 10. The same.

**Comment by firefinchdev** [comment]
Yup, same here. Even the toggle button which changes between @m4heshd dark mode and official dark mode is not there.

**Comment by intraum** [comment]
same here, on macos, white backgrounds, texts not displaying proper colours, everythings pretty hard to read

**Comment by paqua69** [comment]
I tried with the CLI option on MAC - same result as described above

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
