### ISSUE TITLE
Color change only partialy working

### ISSUE THREAD

**Issue by YuvalYarmus** [m4heshd/whatsapp-desktop-dark#183]
After I restarted my computer yesterday and reopened WhatsApp, the dark theme didn't work (often happens) so I just reinstalled. However, unlike usually this time the style change doesn't seem to affect the chats box part (where you can see different chats and groups). 
In addition, the text is written bright grey. 
![Screenshot_3](https://user-images.githubusercontent.com/47609109/77946501-16858c80-72cb-11ea-9ba3-500dca02a23c.jpg)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
