### ISSUE TITLE
Contact theme not set

### ISSUE THREAD

**Issue by ozzysp** [m4heshd/whatsapp-desktop-dark#186]
Hi, m4heshd!
I'm WADark user, it's a great tweak for WhatsApp Desktop!!!
Well, I've been use this for 2 months ago with some issues but not annoying ones, like need reinstall WADark sometimes, but 2 weeks ago, an issue has been appear to scramble Dark Theme. The tweak can't apply modifications on contacts tab, even chats box, with fonts issues. I'm Mac user and my system is a old iMac 2.4 GHz Intel Core 2 Duo with Mac Os El Capitan - 10.11.6
I hope someone can fix this for us, totally noob about coding. 
Thanks for share your knowing. 
![Screen Shot 2020-03-31 at 13 40 40](https://user-images.githubusercontent.com/48163195/78053320-ceac4700-7356-11ea-9523-90603ac4d244.png)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information

**Comment by ozzysp** [comment]
Thanks, UnderEu!
