### ISSUE TITLE
PROBLEM WITH THE INSTALLATION

### ISSUE THREAD

**Issue by JOKERMERONI** [m4heshd/whatsapp-desktop-dark#188]
WHEN I OPEN AFTER I INSTALL WHATSAPPITS MIXING APP THE DARK MODE WITH THE LIGHT/AND THERE ISNT THREE MODE OPTION

**Comment by Act1onH3nk** [comment]
Please check here for a workaround (for now): [https://github.com/m4heshd/whatsapp-desktop-dark/issues/172](url)

What's with the caps btw ;)

**Comment by JOKERMERONI** [comment]
haha I wrote it very late and I didn't pay attention(:

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
