### ISSUE TITLE
No issues. Just wanna know how to uninstall or remove it on windows?

### ISSUE THREAD

**Issue by rajesh-codes** [m4heshd/whatsapp-desktop-dark#19]

**Comment by Slyther** [comment]
I think you can just run the installer again. Should ask you if you want to restore your backup.

**Comment by m4heshd** [comment]
Hi @RajeshCodes, just as @Slyther mentioned you just have to run the script again. It's in the documentation too.

**Comment by rajesh-codes** [comment]
Got it thanks :) @Slyther @m4heshd
