### ISSUE TITLE
this happen to me to

### ISSUE THREAD

**Issue by JOKERMERONI** [m4heshd/whatsapp-desktop-dark#190]
![image](https://user-images.githubusercontent.com/63080288/78353564-eda71500-75b2-11ea-8dd3-a51002465d19.png)

**Comment by Shuja-Mahmood** [comment]
Duplicate of #172

**Comment by JOKERMERONI** [comment]
yes

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
