### ISSUE TITLE
Not applying to all parts of WhatsApp 

### ISSUE THREAD

**Issue by moradizx** [m4heshd/whatsapp-desktop-dark#192]
It installs with no error, but when I open whatsapp, only windows title and chat background changed to dark, the rest are light as before.
![Annotation 2020-04-05 170932](https://user-images.githubusercontent.com/1260563/78471073-f3425d80-7760-11ea-8bfe-e7160264b86a.png)
![InkedAnnotation 2020-04-05 170601_LI](https://user-images.githubusercontent.com/1260563/78471075-f50c2100-7760-11ea-9c07-80b3586d66e1.jpg)

I have checked all the similar issues, but not fixed so far.

**Comment by YuvalYarmus** [comment]
I had the same problem and he suggested a workaround file that you can download and replace. 
The workaround file seems to simply be a style page (like an HTML) so all you have to do is switch the one you have in the path: \WADark-Windows\styles\win32
with the new one. 
It worked for me for like a day and then stopped working for some reason although I tried to do it again for several times including redownloading WhatsApp but hopefully you will have better results.
[0.4.2080-Workaround (2).zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4433257/0.4.2080-Workaround.2.zip)

**Comment by Roobinson** [comment]
Having the same issue here. Perhaps there was an update to WA?

**Comment by cchansk** [comment]
I can confirm that replacing the html file with the workaround worked.

**Comment by chrmey** [comment]
This is a Whatsapp updated related issue. Use the workaround in #172 . 

BTW: Can't you guys check other issues first if they mention your problem before opening a new one? There has been a ton of duplicates to this update-related issue.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
