### ISSUE TITLE
Click for reply becomes irredeemably white

### ISSUE THREAD

**Issue by Lumyn-IT** [m4heshd/whatsapp-desktop-dark#194]
If you click on one message for replay, the clicked message becomes white (with illegible characters white on white) and remain white for ever.

My situation, on Mac OSX Catalina 10.15.4, Whtasapp 0.4.2088 and WADark-macOS with replaced index.html file 0.4.2080-Workaround.zip .

**Comment by Lumyn-IT** [comment]
<img width="1126" alt="Schermata 2020-04-09 alle 17 42 23" src="https://user-images.githubusercontent.com/63413932/78913777-cc01ce00-7a89-11ea-9365-0082440ddeb0.png">

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
