### ISSUE TITLE
double click to answer hopelessly white

### ISSUE THREAD

**Issue by Lumyn-IT** [m4heshd/whatsapp-desktop-dark#195]
If you click on one message for replay, the clicked message becomes white (with illegible characters white on white) and remain white for ever.

My situation, on Mac OSX Catalina 10.15.4, Whtasapp 0.4.2088 and WADark-macOS with replaced index.html file 0.4.2080-Workaround.zip .

<img width="1126" alt="Schermata 2020-04-09 alle 17 42 23" src="https://user-images.githubusercontent.com/63413932/78914353-94475600-7a8a-11ea-8a76-ef6b8b796709.png">

**Comment by UnderEu** [comment]
This is an official theme related issue, there's nothing we can do regarding this theme i.e.
