### ISSUE TITLE
works only partially on MacOS, leaving some parts with the original styles.

### ISSUE THREAD

**Issue by LuanBarrett1** [m4heshd/whatsapp-desktop-dark#196]
Some parts of the application still with their original colors.
I`m using _MacOS Catalina 10.15.4_
WhatsApp version: 0.4.2088

![whatsapp-dark](https://user-images.githubusercontent.com/21247155/78959976-fb80fc80-7ac2-11ea-9889-8e3d167a5f3b.jpg)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
