### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by NocturnalNerd13** [m4heshd/whatsapp-desktop-dark#197]
I´ve used the mod for a month now but every time I close Whatsapp and reopen it goes back to his natural ugly state. Anyway, that's not the issue, the issue is that now it only applies the mod partially. 

. It happens with the telegram look also. It´s Whatsapp from the site, not Windows Store. I logged out by mistake and now because it's partially dark I think that's why my phone isn´t recognizing the QR code.

**Comment by shadowsaintsss** [comment]
yeah man, same thing happening to me.

**Comment by NocturnalNerd13** [comment]
You can log in again if you reinstall it and install it again, but I´m waiting to see if the Mod gets fixed to use the mod again

**Comment by 3raxton** [comment]
@aleamaro791 @Schwipsy check out this workaround. It's been working perfectly for me:

https://github.com/m4heshd/whatsapp-desktop-dark/issues/172#issuecomment-605052347

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
