### ISSUE TITLE
Dont function in Versión 0.4.2088

### ISSUE THREAD

**Issue by ricardogonzale** [m4heshd/whatsapp-desktop-dark#199]
I love this application, but in Version 0.4.2088 in the contact panel it does not update the color to dark, it keeps it light

**Comment by robinterian** [comment]
Also the message bubble's text is white with green background, we'll have to wait till they update this

**Comment by yildirayunlu** [comment]
Fixed this https://github.com/m4heshd/whatsapp-desktop-dark/issues/172#issuecomment-605052347 @ricardogonzale

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
