### ISSUE TITLE
URL colors stay white and don't look clickable

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#2]
![image](https://user-images.githubusercontent.com/13827055/63607194-c8671880-c586-11e9-9a91-4ae2208365a3.png)

**Comment by m4heshd** [comment]
URLs are meant to be white and they do have hover effects. Also those are perfectly clickable. What version of WhatsApp are you on? I'm guessing you're on an older version.

![image](https://user-images.githubusercontent.com/6711514/63608329-52000000-c5f2-11e9-93a9-4d13c0881261.png)

**Comment by KeronCyst** [comment]
Same version as my other issue mention. I thought links were highlighted in blue, not gray, in vanilla WhatsApp.

**Comment by m4heshd** [comment]
It was accent colored in the previous builds but it looked odd and the majority preferred white colored text with hover styles. If you want you can edit the styles yourself easily. 

I've attached a styles file tailored to your need. Just extract the `dark.css` file inside `new_styles.zip` and replace `WADark-Windows\styles\win32\dark.css` with the extracted file. Then rerun the script to install new styles. Make sure to ignore restoring and proceed to a reinstall. See if it looks good for you.

[**new_styles.zip**](https://github.com/m4heshd/whatsapp-desktop-dark/files/3536148/new_styles.zip)

**Comment by KeronCyst** [comment]
Cool, thanks! I'll give it a spin 😄 **EDIT:** Sweet, it works perfectly.

**Comment by KeronCyst** [comment]
How will I be able to know whether this is compatible/incompatible with a future version?

**Comment by m4heshd** [comment]
Hi, I'm happy to let you know that this request has been fulfilled on the latest release. You can check the changes here 3eae5969cc747cb66b29bfcf2f5868bdccfa08e6. Just download the latest release and rerun the script.
