### ISSUE TITLE
Style problems with a whatsapp desktop V0.4.2089

### ISSUE THREAD

**Issue by cristianoronan** [m4heshd/whatsapp-desktop-dark#200]
Many style problems with a whatsapp desktop V0.4.2089 in the macOS version.

<img width="676" alt="Screen Shot 2020-04-14 at 11 12 56" src="https://user-images.githubusercontent.com/20422869/79235123-94a47000-7e41-11ea-9038-8d768815c1e2.png">

<img width="667" alt="Screen Shot 2020-04-14 at 11 12 49" src="https://user-images.githubusercontent.com/20422869/79235108-9110e900-7e41-11ea-8ff1-c8c5716d885e.png">

<img width="1917" alt="Screen Shot 2020-04-14 at 11 13 38" src="https://user-images.githubusercontent.com/20422869/79235130-95d59d00-7e41-11ea-995b-b3f7d539f123.png">

**Comment by anim007** [comment]
![wa dark](https://user-images.githubusercontent.com/11423325/79253400-5775c780-7ead-11ea-973f-939df41dc226.png)
I have same problem with this version. I use default theme.

**Comment by yildirayunlu** [comment]
Fixed this. https://github.com/m4heshd/whatsapp-desktop-dark/issues/172#issuecomment-605052347 @anim007 @cristianoronan

**Comment by cristianoronan** [comment]
Work for me too. Thanks @yildirayunlu

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
