### ISSUE TITLE
theme was not properly applied

### ISSUE THREAD

**Issue by afonsopm** [m4heshd/whatsapp-desktop-dark#201]
I followed all the steps correctly.
No errors were presented.
I tried several themes. All seems to have the same "base" problem.
Follow the img: https://imgur.com/SlsCGne

**Comment by ixxu** [comment]
see here: https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

there is a temporaly workaround.

**Comment by afonsopm** [comment]
> see here: #172
> 
> there is a temporaly workaround.

this worked here, thanks a lot.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
