### ISSUE TITLE
Inverted colors?

### ISSUE THREAD

**Issue by NiNl** [m4heshd/whatsapp-desktop-dark#202]
Hello guys, I have a problem where none of the skins are working properly.
As you can see in the picture the colors look inverted.

I have tried uninstalling WhatsApp multiple times and downloaded a new version of this GitHub, both didnt help.

I would like to hear what I can try to do to fix this, because I really like this tweak.

![image](https://user-images.githubusercontent.com/63954700/79685781-9dc77f80-823b-11ea-9735-6fc1e1f7fb0e.png)

**Comment by NiNl** [comment]
I found this topic with the same problem, also a temporary fix can be found here.
https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
