### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by rj-maitra** [m4heshd/whatsapp-desktop-dark#207]
Opened WhatsApp on MacOS.  Window still dark, but chats lost styling.  Text unreadable.  

Usually when there is an update to WhatsApp, I have to re-run the npm run run-gui command.  This time, it didn't work.  

Uninstalled and re-installed everything—same issue.  Now, GUI installer and Binary installer can't get WhatsApp to run.  

Uninstalling and re-installing everything again.  Will use light theme until fixed.  The "theme" switcher also disappeared.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
