### ISSUE TITLE
Dark mode doesn't work properly

### ISSUE THREAD

**Issue by samuel-prz** [m4heshd/whatsapp-desktop-dark#209]
Some parts of the aplication didn't turn black and some turned into white... 

![Anotación 2020-04-27 231902](https://user-images.githubusercontent.com/57227776/80443792-0b2f7c00-88de-11ea-81dd-e8b156cca8dc.png)

**Comment by KarimTaha** [comment]
Same happened with me, Version 0.4.2088

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
