### ISSUE TITLE
Not Working on Mac with WA version 0.4.2088

### ISSUE THREAD

**Issue by fsan615** [m4heshd/whatsapp-desktop-dark#210]
Bugs on last Whatsapp update  0.4.2088. The screen only show dark mode on a thin line between chats feed and the chat screen

**Comment by ferkrodriguez98** [comment]
Please check https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

There's a workaround. Extract the zip and replace index.html with the new index.html. That'll do it.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
