### ISSUE TITLE
White when clicked.

### ISSUE THREAD

**Issue by ferkrodriguez98** [m4heshd/whatsapp-desktop-dark#211]
I don't know if this happens withtout the workaround of issue #172, but when you click to answer a message it goes white. 

![image](https://user-images.githubusercontent.com/28160560/80665123-f9c9a980-8a6e-11ea-821f-151e5deecb3b.png)

Don't know why that happens 🤷

**Comment by niemant** [comment]
Same here!

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
