### ISSUE TITLE
Not 100% working

### ISSUE THREAD

**Issue by xXPerditorXx** [m4heshd/whatsapp-desktop-dark#214]
My problem is that just the startscreen dark, but if WhatsApp startet everthing is white except on the top left of my profile picture

**Comment by moshevayner** [comment]
Having the same issue here. 
WhatsApp version 2.2017.6

**Comment by Th3Ph4nt0m** [comment]
I have a similar error, also on Windows. For me, the chat frame is displayed correctly, but the selection of the individual chats is not.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
