### ISSUE TITLE
almost working

### ISSUE THREAD

**Issue by phardy2410** [m4heshd/whatsapp-desktop-dark#216]
installed latest 32bit version of whatsapp from their website, applied macos theme as its darkest and the theme doesnt quite apply to all the sections

I tried the other themes and got the same issue, see attached image (msg contents deleted)

https://ibb.co/8MWSdwr << image

**Comment by CoolPuck** [comment]
Same issue here :(

Both using GUI and legacy commandline

**Comment by Th3Ph4nt0m** [comment]
I have a similar error, also on Windows. For me, the chat frame is displayed correctly, but the selection of the individual chats is not.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
