### ISSUE TITLE
AGAIN: Contact panel (left) & in chat name panel are now WHITE (not dark)

### ISSUE THREAD

**Issue by algotr8der** [m4heshd/whatsapp-desktop-dark#217]
This is an issue that occurred before. Apparently the problem is back.

WA Dark Version v0.4.930
Whatsapp Desktop version: 2.2017.6
OS is MacOS 10.15.2 Catalina

![image](https://user-images.githubusercontent.com/1220850/81025122-99a67f00-8e43-11ea-8bf9-8a67fa5fbbd6.png)

**Comment by sakul0807** [comment]
Hello,
use this file to get it back to work![
[0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4582717/0.4.2080-Workaround.zip)
](url)

**Comment by sakul0807** [comment]
Hello,
use this file to get it back to work.

[0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4582724/0.4.2080-Workaround.zip)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
