### ISSUE TITLE
half darkmode

### ISSUE THREAD

**Issue by AimPizza** [m4heshd/whatsapp-desktop-dark#218]
when I run the program, only some parts are actually dark and when I press restore it stays broken

**Comment by AimPizza** [comment]
I got it to work by replacing the index file

**Comment by OliverGronowski** [comment]
How did you do it exactly? What does index mean? I have the same issue I guess. the left column where the conversations are listed are white and the background of the chat is black, also the text of the text bubbles is pale. A step by step would be very useful! Thanks in advance

> I got it to work by replacing the index file

**Comment by OliverGronowski** [comment]
Here is how it looks like for me: [Link to video file](https://imgur.com/a/ZD1Ep2N)

**Comment by AimPizza** [comment]
I think you are german so its easier for me to write german.
In dem Problem unter mir (glaube ich) hatte jemand so ein problem, da wurde von einem Mod die besagte index datei angehangen, welche du unter D:\WADark-Windows\styles\win32 ersetzt.
