### ISSUE TITLE
a few places are still white. 

### ISSUE THREAD

**Issue by xLogiiCx** [m4heshd/whatsapp-desktop-dark#219]
some places in my whatsapp web with enabled dark mode are white.
- the search bar and the square around it is white.
- the text if no chat is open is white.
- if i seatch for a chat every result is white. 

this also happens after restarting pc and whatsapp, reinstalling or using a different theme. 

i use version "0.4.930" and whatsapp version 2.2017.6.
![pic](https://user-images.githubusercontent.com/36159014/81226898-d6ad7580-8feb-11ea-98f9-e1263f8afd0b.PNG)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
