### ISSUE TITLE
Wrong colours

### ISSUE THREAD

**Issue by Julizockt1603** [m4heshd/whatsapp-desktop-dark#221]
-I can´t see the username
-The list of the contacts is still white
-Messages are hard to read
-The contacts in the left are shown as normal I just censored them
![Anmerkung 2020-05-07 191734](https://user-images.githubusercontent.com/64979726/81324859-d79be100-9097-11ea-9e54-88a91961ac66.png)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
