### ISSUE TITLE
Styles not working like should

### ISSUE THREAD

**Issue by nevespt** [m4heshd/whatsapp-desktop-dark#222]
The box of contacts is not working like on the screenshots of this github
Themes tested: MacOS, Deep Black and Whatsapp dark... all with the same issue
Image: 
![Image of Prove](https://i.ibb.co/LRgqWsw/Sem-nome.png)

**Comment by nevespt** [comment]
kinda fixed by adding
`    --panel-background-lighter: var(--bgcol);
    --background-default: var(--darker);
    --background-default-active: var(--darker);
    --primary-strong: var(--lighter);
    --secondary-stronger: var(--light):`
to the css root

**Comment by meechgalhuquot** [comment]
This is broken for me as well in a basically Identical way

**Comment by JulesEtienne** [comment]
Any chance you could help me out with some more details on how to "add [...] to the css root? Thanks in advance :-)

**Comment by Abi667** [comment]
Unfortunately I have the same issue. Using WADark 0.4.930 and client version 0.4.2088

**Comment by pato-gonzalez** [comment]
this worked for me so far 
https://github.com/m4heshd/whatsapp-desktop-dark/issues/172#issuecomment-605052347

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
