### ISSUE TITLE
Not working properly.

### ISSUE THREAD

**Issue by SheroxGG** [m4heshd/whatsapp-desktop-dark#224]
After the last update a month ago my dark whatsapp broke, some features like the moon disappeared and now all the chats are on white, and the messages aswell. Just the background is black, and the messages are imposible to read. Hope you can help me, thanks!

**Comment by Koolstr** [comment]
Having the same issue. 
Is this being worked on? Have you at least been able to reproduce it?

**Comment by alistair-low** [comment]
@SheroxGG @Koolstr if you look at issue #172, there is a workaround to this problem.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
