### ISSUE TITLE
MacOS Catalina 10.15.4 & Whatsapp 2.2019.6

### ISSUE THREAD

**Issue by JoeyOverby** [m4heshd/whatsapp-desktop-dark#225]
It hasn't been working for awhile, so I did the following to make sure there was not lingering issues. 

**Configuration:**
MacOs : Catalina 10.15.4
WhatsApp: 2.2019.6
WADark version: 0.4.930

1) Removed all WADark downloads/folders
2) Removed WhatsApp from Application folder (uninstalled it)
3) Restarted Computer
4) Re-downloaded Whatsapp, back to normal view
5) Re-downloaded Whatsapp installer, (info.json says version is 0.4.930). 
6) Stopped Whatsapp
7) Ran installer said everything was fine. 

![image](https://user-images.githubusercontent.com/38049004/81727278-f0b0e300-9445-11ea-8864-a90694dc2a67.png)

But as you can see, the chat groups on the left are not affected, and the color scheme is all messed up and pretty much unreadable. (top message I left alone and the color scheme is all messed up). 

Also tried running installer as sudo. 
- Ran successfully, but then I cannot get past the verification window to add whatsapp web as the whatsapp icon in the middle of the QR code is the wrong color so my phone doesn't understand the QR code. 
- That instance of WhatsApp is running as root (which makes sense since the installer was ran with sudo). However when I close that instance, and try to re-open WhatsApp it starts as my username (which is what it should be doing, but the styles are like the previous attempt to run script as non-root). 

This is the same issue I've been seeing for a few months now, and no matter what style I choose it does not change that left hand side (chat selection area) color scheme at all. 

If you would like me to try things, get logs, etc, let me know and I'll gladly help out. I don't program much in js, but can likely still help out with trying things. And I didn't see any log files in the directory, or I would've included them.

**Comment by anacona16** [comment]
See https://github.com/m4heshd/whatsapp-desktop-dark/issues/172

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
