### ISSUE TITLE
Theming Stopped Working on Whatsapp v2.2019.8

### ISSUE THREAD

**Issue by Manas73** [m4heshd/whatsapp-desktop-dark#226]
My whatsapp just got updated to version 2.2019.8 and the dark theme stopped working. I did re-apply the theme (with and without the workaround), but it looks like this:
![image](https://user-images.githubusercontent.com/56934475/81955782-257c9000-9628-11ea-9564-39dc700d0f2a.png)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
