### ISSUE TITLE
Not dark completely.

### ISSUE THREAD

**Issue by GooglesXmaddness** [m4heshd/whatsapp-desktop-dark#227]
Hello, I have an Issue where my whatsapp desktop app has white parts not changed to black. Details in screenshot **below**. Bsically, side bar with selecting chat and text boxes are remaining white.

https://imgur.com/a/tMI6iwX

**Comment by Kozek** [comment]
The client is just a wrapper for the original [web app](https://web.whatsapp.com). 
This means there is just the HTML and CSS text represented in a web view as a standalone application.

To apply a darkmode onto these, we need to overwrite the original css with the modified dark mode one.
Whenever WhatsApp changes some class names in their html text, the modified css applies color etc. onto an element which is not reachable via the old class.

The result is that some parts stay unaffected.

Someone has to update the class names in [master/styles/win32/dark.css](https://github.com/m4heshd/whatsapp-desktop-dark/blob/master/styles/win32/dark.css).

Already tried it but my knowledge about the structure and relations between those class names are not enough.

**Comment by Kozek** [comment]
The way of updating the modified dark.css every time when whatsapp rolls out some changes is always behind the real state. So the workaround is to invert the colors.

Workaround:

1. Restore WhatsApp Theme to default
2. Navigate into WADark-0.4.930-Windows\WADark-Windows\styles\win32
3. Edit the dark.css file with Editor, Notepad++, VSCode or similar app
4. Replace the entire content with [workaround dark.css](https://gist.github.com/Kozek/34541c88d5d9f4df0c4c20e818a74ba1)
5. Start WADark.exe and select WhatsApp Dark as Theme

This will invert the colors but also the emojis too.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
