### ISSUE TITLE
It's only sligtly dark on ver. 0.4.930 Windows

### ISSUE THREAD

**Issue by VladC12** [m4heshd/whatsapp-desktop-dark#228]
https://imgur.com/a/fZUDFYG

**Comment by Kozek** [comment]
Might be the same as in #227 
I'll post a workaround there in a couple of minutes.

Edit: [workaround](227#issuecomment-629242859)

**Comment by spacekcraft** [comment]
Same problem

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
