### ISSUE TITLE
Title too Dark, Contacts pane and message bubbles not dark in macOS Version 2.2019.8

### ISSUE THREAD

**Issue by renecum** [m4heshd/whatsapp-desktop-dark#229]
Here is a small screenshot show this problem.

1. The title of the active conversation is too dark.
2. The contact list is not dark.
3. The bubbles are not dar either.

I've tried different themes in v0.4.930 of Whatsapp Desktop Dark and Version 2.2019.8 of Whatsapp for macOS.

![whatsapp-darkmode-not-working](https://user-images.githubusercontent.com/670045/82098602-7f319880-96c2-11ea-9503-fc27a9fee826.png)

**Comment by RyanGuyCode** [comment]
For me too-- text is too faint.
![Screen Shot 2020-05-16 at 3 53 18 PM](https://user-images.githubusercontent.com/23059787/82130092-c5076300-978d-11ea-8730-874034c44c5d.png)

**Comment by denahardian** [comment]
same issue on windows, im recently restore my backup hope this issue fixing soon :D

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
