### ISSUE TITLE
Font on status captions, while replying, is not clearly visible.

### ISSUE THREAD

**Issue by mrillusi0n** [m4heshd/whatsapp-desktop-dark#23]
![image](https://user-images.githubusercontent.com/37063502/64666411-d6b4a000-d473-11e9-8069-d6817c0a7d82.png)
The font at the bottom needs to be of a darker colour.

**Comment by m4heshd** [comment]
Hi @mrillusi0n,
I can confirm this issue and It'll be fixed in the next release. Thanks for reporting.

**Comment by mrillusi0n** [comment]
@m4heshd I can see the same issue when I'm using "@" functionality in group chats.

**Comment by m4heshd** [comment]
I'm guessing It's similar to https://github.com/m4heshd/whatsapp-desktop-dark/issues/13. Can you post a screenshot?

**Comment by mrillusi0n** [comment]
Yes. It is. But here, I have a screeny. Full contact name is **Itano**. **no** is not visible.

![image](https://user-images.githubusercontent.com/37063502/64837345-ac95e600-d60b-11e9-9ea9-97caa33ac87b.png)

**Comment by m4heshd** [comment]
Ok i can confirm this issue but only on mac. This'll be fixed with issue #13. Thanks for reporting.

**Comment by m4heshd** [comment]
The original issue you raised is fixed in 56b159217d59592d90225178843953822190659e and the 2nd issue is also fixed in 783eb39e42166e4f1233c3b4ea0d8496cd2e43fe. Both of the fixes are now available in the latest release. Closing this thread.
