### ISSUE TITLE
Background Doodle Missing Version 2.2019.8

### ISSUE THREAD

**Issue by pasayev** [m4heshd/whatsapp-desktop-dark#230]
Hello,
Background Doodle is missing in whatsapp version 2.2019.8. It shows only dark solid color.

**Comment by pasayev** [comment]
I edited files for macos version. Now background doodle appears normally. Just download latest version and change index.html and dark.css.

[replace.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4638498/replace.zip)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
