### ISSUE TITLE
Chat and search bar remain white

### ISSUE THREAD

**Issue by NST92** [m4heshd/whatsapp-desktop-dark#231]
I've tried multiple themes, all face this problem for me.
I've followed the instructions and downloaded the app from the provided link.

**Comment by NST92** [comment]
Furthermore, the text has really low contrast, barely readable

**Comment by ghost** [comment]
Everyone is having this problem. I'm going to try editing the colors in override.json and I'll get back to you.

Edit: yeah I can't find a way to get rid of white without messing with the fundamental part of the css. will update if I find a way. 

2nd Edit: https://github.com/m4heshd/whatsapp-desktop-dark/issues/172 worked for me as a temporary fix.

**Comment by conformist1** [comment]
And to add on to this, when I try changing to different themes (original install was on MacOS X Catalina), WhatsApp won't open unless I 'restore'. Thank you so much for working on this!!

**Comment by ghost** [comment]
> And to add on to this, when I try changing to different themes (original install was on MacOS X Catalina), WhatsApp won't open unless I 'restore'. Thank you so much for working on this!!

You are using an outdated version of the installer (I believe - I got the error on windows when I used an outdated installer so I assume it's the same issue)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
