### ISSUE TITLE
Default dark mode isn't really dark on Windows 10

### ISSUE THREAD

**Issue by rmed1na** [m4heshd/whatsapp-desktop-dark#233]
Most of the content is still white.

My setup:
Windows 10 Pro
Whatsapp Desktop v2.2019.8

![image](https://user-images.githubusercontent.com/30838319/82267145-27e52f80-9931-11ea-91a7-7b85f52cb9e7.png)

**Comment by SemenBogdanov** [comment]
Have the same trouble

**Comment by devilishlyn** [comment]
Same issue as well... Mine it's just like the one in the OP attachment...
I didn't knew about this project and now I can't wait to use it... I'll be checking here for fixes...
thanks!

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
