### ISSUE TITLE
Colour of the in text font is very light grey

### ISSUE THREAD

**Issue by PRINCEdevon** [m4heshd/whatsapp-desktop-dark#234]
Hey there just a quick report on user experience.

The font colour used of the chat on the Win10 is a very light grey. 
Specifically with both the dark themes.
 
Its very difficult to read what you or they said - dont know if there is a work around that I missed - have had to return to default, which is a huge shame because the theme was looking great but cant read anything from the chat without great strain!

Thank you in advance if you manage to fix this - will check back for sure!

Lots of love

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
