### ISSUE TITLE
Issues / don't expect a solution here...

### ISSUE THREAD

**Issue by tentaurus** [m4heshd/whatsapp-desktop-dark#237]
Very soon Dark Mode willl be part of the official desktop app!
No more need to use this hack! Which currently doesn't work anymore...
Be patient!

**Comment by roceb** [comment]
Well the beauty of this ~~hack~~ mod. Is that you can use any color scheme you want.

**Comment by holymode** [comment]
I dont like the official color scheme.

**Comment by m4heshd** [comment]
You need to be able to read through the issue tracker before using the tracker itself as a forum. Closing this.
