### ISSUE TITLE
its not working for me not all parts

### ISSUE THREAD

**Issue by PromHeda** [m4heshd/whatsapp-desktop-dark#239]
![Screenshot_1](https://user-images.githubusercontent.com/65893013/82795498-c8c97280-9e7c-11ea-8207-1bf42e70637b.png)
as you can see it didnt change left side also it didnt change text boxes Windows 10 pro

**Comment by keshavdutt1990** [comment]
exactly the same issue with me ,the contacts are not in dark mode everything else is okay

**Comment by diegoulloao** [comment]
The same issue with 2.2021.2 Whatsapp version!

**Comment by gamrumin** [comment]
Yeah the same

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
