### ISSUE TITLE
Followed the step and installed via CLI - Screen is odd but.

### ISSUE THREAD

**Issue by sanjaypradeep** [m4heshd/whatsapp-desktop-dark#244]
Opted for (1. Deep Darkmode) via CLI

This how it's looking like, Please take a look, 
![image](https://user-images.githubusercontent.com/18122757/83358339-77474900-a390-11ea-9b8e-91a41922c43e.png)

Can you please help me how to overcome this? much helpful and appreciated.

I'm available anytime, we can sync up.

**Comment by antoniohenriqueac** [comment]
i had the same problem!!

But i solve with this link:
[https://github.com/m4heshd/whatsapp-desktop-dark/issues/242](url)

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
