### ISSUE TITLE
Greyed out text and contact list still bright

### ISSUE THREAD

**Issue by stephenaustin** [m4heshd/whatsapp-desktop-dark#249]
Thanks for addressing a long standing issue which Whatsapp is showing respect for its users by ignoring. 

Upon installation I found the text in the messages were greyed out and hard to read, but not illegible. And the contact list / conversation list on the left still had a bright background. 

Thanks for your attention.

**Comment by UnderEu** [comment]
Duplicate issue. See #172 for further information
