### ISSUE TITLE
Whatsapp still LIGHT

### ISSUE THREAD

**Issue by TheJokerArtZ** [m4heshd/whatsapp-desktop-dark#252]
Hi i installed #242 and also some custom "mods" but the ony thing thats changeing ist this https://prnt.sc/sxt62i

PLS HALP :)

**Comment by vitorpvcampos** [comment]
Almost the same here. The user list is still white.

**Comment by rj-maitra** [comment]
Did you go into SETTINGS > CHATS > THEME > DARK?

**Comment by TheJokerArtZ** [comment]
oh wow xD

> Did you go into SETTINGS > CHATS > THEME > DARK?
