### ISSUE TITLE
This Is *NOT* THE END

### ISSUE THREAD

**Issue by NCheok** [m4heshd/whatsapp-desktop-dark#257]
https://9to5mac.com/2020/07/01/whatsapp-dark-mode-mac-animated-stickers-qr-codes/ - Facebook has now announced officially desktop versions will now be Dark Mode enabled, definitely they would have taken inspirations and guidance from here.

I personally have put alot of faith behind @m4heshd where it counts $ and have enjoyed his project and contribution from when this started, at the tail end of things, at least for the past 3 months, I've stopped using this code as it is often broken, requires endless patching and definitely a shift of focus by @m4heshd to keep this project going.

With that, it's time for me to sign out. Thank you sincerely @m4heshd.

**Comment by NicolasPL64** [comment]
@m4heshd has been a god. Thanks.

**Comment by UnderEu** [comment]
Who said this is the end? This mod is many more than “just a darker green theme”. I’m still waiting for ‘Deep Black’ to be updated, among the other options.
