### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by ritvij14** [m4heshd/whatsapp-desktop-dark#259]
I searched for this, but I saw solutions in previous issues that they were for macOS. I am on windows and this is what I get-

```
$npm install

> resourcehacker@4.2.51 postinstall C:\Users\hp\Desktop\Github\whatsapp-desktop-dark\node_modules\resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:141
  let expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:141:39)
    at request (http.js:46:10)
    at Object.get (http.js:50:15)
    at Object.<anonymous> (C:\Users\hp\Desktop\Github\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-07-06T13_16_40_850Z-debug.log```

**Comment by luisantos1986** [comment]
> I searched for this, but I saw solutions in previous issues that they were for macOS. I am on windows and this is what I get-
> 
> ```
> $npm install
> 
> > resourcehacker@4.2.51 postinstall C:\Users\hp\Desktop\Github\whatsapp-desktop-dark\node_modules\resourcehacker
> > node scripts/install.js
> 
> Downloading ResourceHacker by Angus Johnson...
> _http_client.js:141
>   let expectedProtocol = defaultAgent.protocol;
>                                       ^
> 
> TypeError: Cannot read property 'protocol' of undefined
>     at new ClientRequest (_http_client.js:141:39)
>     at request (http.js:46:10)
>     at Object.get (http.js:50:15)
>     at Object.<anonymous> (C:\Users\hp\Desktop\Github\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
>     at Module._compile (internal/modules/cjs/loader.js:1123:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>     at Module.load (internal/modules/cjs/loader.js:972:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:872:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-07-06T13_16_40_850Z-debug.log```
> ```

this issue has been solved here

https://github.com/m4heshd/whatsapp-desktop-dark/issues/35
