### ISSUE TITLE
OS:WINDOWS Error The specified module was not found.

### ISSUE THREAD

**Issue by Grazyyt** [m4heshd/whatsapp-desktop-dark#26]
I don't know what to do can you help me with that?
![sst](https://user-images.githubusercontent.com/53707570/64906005-b9383e00-d6e0-11e9-8d16-56f68e4aada2.png)

**Comment by Grazyyt** [comment]
@m4heshd can you help me pls

**Comment by m4heshd** [comment]
Hi @Grazyyt,
Can you open up a command prompt window, type `wmic process get ProcessId,ParentProcessId,CommandLine` and hit enter. Post a screenshot of the result.

**Comment by Grazyyt** [comment]
What are you looking for because I don't know what to screenshot there are so many Lines.

**Comment by Grazyyt** [comment]
Are you looking for these lines ?
![Unddddnannt](https://user-images.githubusercontent.com/53707570/64911295-f3750000-d71f-11e9-8f06-02a33419e41d.png)

**Comment by m4heshd** [comment]
Yes indeed. But the problem is it makes this issue more complicated. Any chance you can get the exact English output of the error?

**Comment by Grazyyt** [comment]
> Yes indeed. But the problem is it makes this issue more complicated. Any chance you can get the exact English output of the error?

Maybe if I turn my pc language to english then restarting it and runing the WADark again ?

**Comment by m4heshd** [comment]
Try two more things before you do that. 

1. Open properties for `WADark.exe` and check if this button is available. If it's there, just hit unblock and apply. Then try running it.

![image](https://user-images.githubusercontent.com/6711514/64911363-79a03f00-d73e-11e9-8e58-aba16b9fd79f.png)

2. If the above method didn't work, try running `WADark.exe` as Administrator.

**Comment by Grazyyt** [comment]
1.there is no unblock button
![c](https://user-images.githubusercontent.com/53707570/64911442-0e487400-d722-11e9-9f66-5e405f9c7b09.png)

2.I tried running it as adminstrator and it didn|t work

so turned mz pc language to enlish
![ged](https://user-images.githubusercontent.com/53707570/64911451-31732380-d722-11e9-8533-dc41db0abdee.png)

**Comment by Grazyyt** [comment]
@m4heshd so what to do now ?

**Comment by m4heshd** [comment]
This is a rundll error and It's really strange. Next thing would be to try cloning the source and run it directly from source instead of building binaries. Instructions are [right here](https://github.com/m4heshd/whatsapp-desktop-dark/blob/master/README.md#build-the-installation-script-yourself). Let me know if you need any help.

**Comment by Grazyyt** [comment]
@m4heshd Okay I don't know why but now it worked. Thank you
![fdsfdsd](https://user-images.githubusercontent.com/53707570/64912377-8d43a980-d72e-11e9-9f8d-abdcb6ed2cf1.png)

**Comment by m4heshd** [comment]
This was actually what i was thinking. There must've been one rundll instance hogging a single dll file which was needed by Node.js. Either way glad it finally worked for you. I still wish we were able to pinpoint the issue. A challenge for some other time. 🙂
