### ISSUE TITLE
Upper-right drop-down arrow hard to see with link-preview messages

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#27]
![Clipboard01](https://user-images.githubusercontent.com/13827055/65180447-be172d80-da11-11e9-9b8a-30ec39ce0cb7.png)
![Clipboard02](https://user-images.githubusercontent.com/13827055/65180448-be172d80-da11-11e9-947e-802ca02b93d7.png)

**Comment by m4heshd** [comment]
I'm aware of this but decided to ignore it since it's not much of a problem and if i change it, gonna end up with a chain of issues because then it's going to be hardly visible on many other places. Does it bother you a lot?

**Comment by KeronCyst** [comment]
It doesn't. I was just wondering if it was a matter of which you were aware, and I didn't know that the coloring was linked to other different-colored backgrounds; how annoying. I think users are trained on a basic level enough by regular non-link messages to remember that there is a context button up there so it's not too big of an issue. Too bad that the coloring is unfortunately linked in the problematic way that you described. Oh well, can't have our cake and eat it too. Thanks for responding so quickly.

**Comment by m4heshd** [comment]
Lemme look into this in the next release. I'll try to highlight it up a bit without triggering any 3rd party complications. I'll keep this noted.
