### ISSUE TITLE
Add acrylic/Mica effect

### ISSUE THREAD

**Issue by bigplayer-ai** [m4heshd/whatsapp-desktop-dark#272]
Heym
Can you add fluent (Add acrylic/Mica effect) theme support for whatsapp desktop?
Feature request: Add acrylic/Mica effect whatsapp so it is more tailoed to the windows 11
![Whatsapp Light](https://user-images.githubusercontent.com/119108387/220302687-77ad8796-516f-4284-a272-0f66742bfa4a.png)

![WhatsApp Dark](https://user-images.githubusercontent.com/119108387/220302491-c421faff-26d2-436a-9fd8-437ae6518faf.png)

**Comment by m4heshd** [comment]
Hi @bigplayer-ai,

Unfortunately, this project isn't in active development anymore. Also WhatsApp desktop has transitioned to native design from Electron. So it's pretty much impossible to do modifications on it now. Closing this.
