### ISSUE TITLE
White background when searching for emojis.

### ISSUE THREAD

**Issue by OBadstue** [m4heshd/whatsapp-desktop-dark#28]
When searching for emojis using ':' the whole ribbon that opens is white. Not sure if this is just due to the fact that the WEBP with emojis have white backgrounds.

![WADark GUI error](https://user-images.githubusercontent.com/55435450/65244640-503f3480-daeb-11e9-89bc-5b188f5a3116.jpg)

**Comment by m4heshd** [comment]
Hi @OBadstue,
I can confirm It's something I've missed. Fix will be in the next release but unfortunately as you mentioned, it will be a partial fix. Take a look.

![image](https://user-images.githubusercontent.com/6711514/65247664-6d392f00-db0e-11e9-90c9-4ca0cd36eaf6.png)

The WEBP issue will still be there even after i fix this. Sorry about that. 😕

**Comment by m4heshd** [comment]
Hi, The fix for this issue is implemented in 777c1d0b5fc2a8e728dea9981caeba492a3a1bac and it's available in the latest release. Thanks for reporting.
