### ISSUE TITLE
New Whatsapp Update Overwrites MOD...

### ISSUE THREAD

**Issue by joaoavilars** [m4heshd/whatsapp-desktop-dark#30]
after new update of Whatsapp, applied again WADark, applied without problems.
After a few minutes, the update message appeared again ...
Is this normal or is it disabled?

**Comment by NicolasPL64** [comment]
same

**Comment by m4heshd** [comment]
That's odd. Didn't happen to me. Does it keep happening if you install the dark mode?

**Comment by NicolasPL64** [comment]
Yes, it says there's a new version available

**Comment by m4heshd** [comment]
Even if you install the dark mode multiple time? I've talked to a few users but none of them have this issue including me. Maybe wait for the next release which I'll be doing in a few hours.

**Comment by NicolasPL64** [comment]
Yep, I've installed it twice. I saw it created another WA folder with the version. I'll be waiting for the new update then ;)

**Comment by joaoavilars** [comment]
Awaiting looking forward here!

**Comment by m4heshd** [comment]
I have a little suspicion. Did any of you by any chance restore WhatsApp to original version accidentally before installing the dark mode on latest version using the same script you used to install dark mode on previous version? @NicolasPL64 that explains the new directory.

**Comment by m4heshd** [comment]
Just released the latest update. Do test and let me know.

**Comment by NicolasPL64** [comment]
THANKS! Let me see

**Comment by NicolasPL64** [comment]
Yep, after using it for hours, I can tell everything is fine again. Thanks!

**Comment by m4heshd** [comment]
@NicolasPL64 That's good news. I'm closing this thread.
