### ISSUE TITLE
Email addresses not showing up in chat

### ISSUE THREAD

**Issue by Abi667** [m4heshd/whatsapp-desktop-dark#33]
Hey!
So... with the latest version of your code and the latest version of whatsapp, the emails are no longer visible in the chat window. The language in the screenshots is Romanian but the issue should be culture invariant :D. The view is from both sides. Other than that, big thanks for what you're doing!

![image](https://user-images.githubusercontent.com/18659624/65434420-73d5e800-de27-11e9-9918-5f161f43a886.png)
![image](https://user-images.githubusercontent.com/18659624/65434455-82bc9a80-de27-11e9-9221-5d027fd1b677.png)

**Comment by mcsomenzari** [comment]
A few minutes ago the Whatsapp app was updated and the problem was fixed.

**Comment by m4heshd** [comment]
As @mcsomenzari mentioned this bug was on WhatsApp release itself. Closing this since it's an external issue and already been fixed.
