### ISSUE TITLE
An Error during build the app on Windows

### ISSUE THREAD

**Issue by Kadantte** [m4heshd/whatsapp-desktop-dark#35]
Hi, I tried to build the app on Windows but there is a problem when I use `npm install` so the problem is:

```shell
C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark (master) (whatsapp-desktop-dark@0.3.4678)
λ npm install

> resourcehacker@4.2.51 postinstall C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark\node_modules\resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:131
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:131:39)
    at request (http.js:44:10)
    at Object.get (http.js:48:15)
    at Object.<anonymous> (C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely
```
I know there's an issue similar to this one but in macOS ( #11 #25 #31 ), I already contacted the Dev of this module ([resourcehacker](https://github.com/felicienfrancois/node-resourcehacker)) via E-Mail also I opened an issue on the repo too but unfortunately the repo did not get any updates from  Feb 11, 2016, so I don't if the Developer will reply to my issue or E-Mail. If you know a way how to prevent this problem from happening please let me know.
N.B:
OS: Windows 10 1903
node: 12.10.0
npm: 6.10.3
yarn: 1.17.3

**Comment by m4heshd** [comment]
Hi @Kadantte,
It's really weird that some users started to get the postinstall script error from that module on Windows too. Take a look at this [Reddit post](https://www.reddit.com/r/whatsapp/comments/d757p1/help_is_there_any_possible_way_to_change_the/)  where another user had a similar issue. Just like i suggested there, you may have to uninstall the dependency and continue the process. 

I was thinking of removing this module completely and adding the reshacker binary file to the repo as an asset. But Angus Johnson's licence policies prevent me from doing that. Still thinking of a way to get rid of the module. I'll be digging deeper.

**Comment by Kadantte** [comment]
It works, So the problem was from cmder and windows cmd I dunno why but Windows Powershell is working fine!
```shell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> cd C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark
PS C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark> npm uninstall resourcehacker
audited 2416 packages in 32.522s
found 0 vulnerabilities

PS C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark> npm install
audited 2416 packages in 10.909s
found 0 vulnerabilities

PS C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark> node .

~~~~ WhatsApp Desktop Dark Mode by m4heshd ~~~~


Checking for dark mode updates.. (Current version - v0.3.4678)

This process takes at least a minute to complete. So please be patient and let it do the magic..

WhatsApp process not found. Make sure WhatsApp desktop is running before installing dark mode.

Press any key to exit..
```

**Comment by m4heshd** [comment]
Closing this since the issue is solved.
