### ISSUE TITLE
Double-Checkmark Colors for "Read" vs. "Delivered" are the same color

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#36]
"Read" used to be blue, but now they're both gray.

**Comment by m4heshd** [comment]
Works fine for me on the latest version

![image](https://user-images.githubusercontent.com/6711514/65462328-37c87480-de73-11e9-901a-ada005915b33.png)

Maybe the other party must have read receipts turned off.

**Comment by KeronCyst** [comment]
Okay, it's really faintly lighter-gray. It's definitely not blue and it definitely wasn't like this before. I'm not sure of what's going on but it looks like this:

![image](https://user-images.githubusercontent.com/13827055/65530270-7af30980-deac-11e9-9486-b7318b0cfb79.png)

(And it's hard to tell...)

**Comment by m4heshd** [comment]
Ok i have a guess. Did you change the accent color to that gray? Because the "Read ticks" are meant to be accent colored.

**Comment by KeronCyst** [comment]
Ahhhhhh. Yes, I typed "gray" (or "ggrraayy" as it appeared, haha). What is the default color? That should probably be mentioned in the script when it prompts for an accent...

**Comment by m4heshd** [comment]
It gives you a binary option to customize the color which is a Y or N. So no need for mentioning the default color.
