### ISSUE TITLE
New Version 0.3.4679 Works With Dark Mode 0.3.4678 (Not An Issue)

### ISSUE THREAD

**Issue by NCheok** [m4heshd/whatsapp-desktop-dark#37]
Thanks Mahesh for releasing an update for 0.3.4678 ... Looks like FB pushed a new version out again today. Didn't want to update it and break the dark mode again until you have verified it is safe to proceed.

**Comment by NicolasPL64** [comment]
![image](https://user-images.githubusercontent.com/31411531/65472190-df27b600-de37-11e9-91d1-9009213c101d.png)

I got this again xDD

(It says there's a new update)

**Comment by m4heshd** [comment]
Hi @NCheok,
Nothing to worry. Go ahead and do the update. Dark mode [v0.3.4678](https://github.com/m4heshd/whatsapp-desktop-dark/releases/tag/0.3.4678) works perfectly fine with WhatsApp desktop v0.3.4679. Thank you for the wonderful support on ko-fi. ☕😊

**Comment by m4heshd** [comment]
@NicolasPL64, Your WhatsApp desktop installation seems to be broken at this point because of the incorrect directory structure created by Squirrel Windows. WhatsApp apparently have messed up the latest release. And on top of that, I'm guessing the dark mode installation script must've restored the source file from the previous version inside the directory of latest version. Really sorry about that. Can you try a fresh installation?

**Comment by NicolasPL64** [comment]
![image](https://user-images.githubusercontent.com/31411531/65472411-fa46f580-de38-11e9-96b9-14144616b217.png)

I think that too

**Comment by NCheok** [comment]
> Hi @NCheok,
> Nothing to worry. Go ahead and do the update. Dark mode [v0.3.4678](https://github.com/m4heshd/whatsapp-desktop-dark/releases/tag/0.3.4678) works perfectly fine with WhatsApp desktop v0.3.4679. Thank you for the wonderful support on ko-fi. ☕😊

You are very welcome Mahesh.

I confirm 0.3.4679 on OSX works perfectly with your Dark Mode release 0.3.4678, appreciate the prompt verification and confirmation.

**Comment by m4heshd** [comment]
@NicolasPL64, Seems like it. Also never extract the dark mode script inside WhatsApp installation directory. Keep the script related files somewhere else. It'll work fine anywhere inside your filesystem.

**Comment by NicolasPL64** [comment]
Oh, I didn't know that. Thanks!
