### ISSUE TITLE
[POLL] Should the title bar on Windows version look dark instead of being accent colored?

### ISSUE THREAD

**Issue by m4heshd** [m4heshd/whatsapp-desktop-dark#38]
It'll look like this :

![image](https://user-images.githubusercontent.com/6711514/65543610-1b8a0d80-df2f-11e9-9e94-f62f1214e10b.png)

**UPDATE :** 
New plan is in the works to make the title bar a darker version of accent color chosen by the user. For an example, default color would look like this : 

![image](https://user-images.githubusercontent.com/6711514/65713711-6040b080-e0b7-11e9-8a1a-952912a08de9.png)

Vote by clicking on the options 👇
[![](https://api.gh-polls.com/poll/01DNJBJMTHXDV1SV7CRVQR2BP8/Yes)](https://api.gh-polls.com/poll/01DNJBJMTHXDV1SV7CRVQR2BP8/Yes/vote)
[![](https://api.gh-polls.com/poll/01DNJBJMTHXDV1SV7CRVQR2BP8/No)](https://api.gh-polls.com/poll/01DNJBJMTHXDV1SV7CRVQR2BP8/No/vote)

**Comment by KeronCyst** [comment]
~I picked "no" because even though I like that specified color, I like the customization more. It should be made a default option if nothing custom is entered, but I prefer not being forced, too.~

Oops, never mind; it already says this but for some reason I didn't see it the first time!

**Comment by revi97** [comment]
nice poll idea, but looked around and made the changes already to the app though.  Got stuck in seen messages so had to make some changes

**Comment by m4heshd** [comment]
@revi97 I've already posted it on https://github.com/m4heshd/whatsapp-desktop-dark/issues/5#issuecomment-527501736 few weeks back but this is mostly for the regular users who are not capable of editing CSS on their own.

**Comment by revi97** [comment]
Oh yeah, just saw it. Thanks for the information.

**Comment by timea-techgirl** [comment]
@m4heshd Can you give me the color code for darker version of official whatsapp teal title bar?
I think this is the original teal: #2CBDA5

**Comment by m4heshd** [comment]
@timeakesmarky you can use [this tool](https://pinetools.com/darken-color) for now.

**Comment by m4heshd** [comment]
This has been decided and implemented in the latest release.
