### ISSUE TITLE
Selected/Highlighted text is hard to see

### ISSUE THREAD

**Issue by KeronCyst** [m4heshd/whatsapp-desktop-dark#39]
The following text is highlighted by mouse for copying, but I can barely see the highlight:

![image](https://user-images.githubusercontent.com/13827055/65555586-e1dee580-dee1-11e9-9148-877f88385d1c.png)

**Comment by m4heshd** [comment]
That's odd. Perfectly fine on mine.

![image](https://user-images.githubusercontent.com/6711514/65557034-75023480-df4f-11e9-83c6-b5d4810c877f.png)

The selection highlight is usually inherited from system which means this is related to your platform.

**Comment by KeronCyst** [comment]
I'm not sure of what happened. I used default settings with no backup
restoration and am on the latest WhatsApp version for Windows 10...

>

**Comment by m4heshd** [comment]
Oops. I forgot that selection is overridden to use the accent color. You can simply search and change this inside the dark.css.

```
::selection {
    color: var(--light) !important;
    background-color: var(--accent) !important; 
}
```

Really sorry about the confusion.
