### ISSUE TITLE
Is this on purpose?

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#42]
![image](https://user-images.githubusercontent.com/31411531/65728436-97e03600-e080-11e9-86c7-c414f05b1c0e.png)

The white borders

**Comment by m4heshd** [comment]
Hi @NicolasPL64,
This is a duplicate of issue #6 and you can get updated on there. Also it's currently being discussed on https://t.me/wadarkmodechat
