### ISSUE TITLE
I don't know when I/he have/has listened an audio

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#43]
![image](https://user-images.githubusercontent.com/31411531/65797663-6ecdad00-e135-11e9-9b35-bbe6c399362a.png)

The color still is the same

**Comment by NicolasPL64** [comment]
Note: He listened that audio

**Comment by m4heshd** [comment]
Hi @NicolasPL64,
I can confirm this issue and It'll be fixed in the next release. Thanks for pointing it out.

**Comment by m4heshd** [comment]
The issue has been fixed in 81a9533b5c3c0877daf4176771842a38d474a6eb.
