### ISSUE TITLE
Fix issue in RTL (Right To Left)

### ISSUE THREAD

**Issue by Idomo** [m4heshd/whatsapp-desktop-dark#46]
Hi,
First of all, great addon, saved my eyes!
About a year ago, WhatsApp decided to do unclear thing and changed the position of the 3 buttons (red, yellow, green) to the left, even when the system's & app's main language is an RTL language (like Hebrew).

Well, after sending their support a few bug reports and they told me it has been done on purpose (what I can’t believe is true, you may see the screenshot and think so yourself).
The fix should be very easy with CSS (I guess it's just some `float: right;`), so I'd really appreciate if you'll add it to the addon and make it the best thing WhatsApp could have (;

Image for illustration (Its more noticeable in light theme, but still blocking some functionality on both light and dark):
![Screenshot at Jun 06 10-53-42](https://user-images.githubusercontent.com/26777129/66086097-c88e0700-e57b-11e9-83f6-99173feb8c89.png)

Thanks,
Ido.

**Comment by m4heshd** [comment]
Hi @Idomo,
This is not something that can be fixed by us. WhatsApp developers need to fix this because window control buttons aren't added through the graphical part of coding but the functional coding and OS itself. Really sorry about that.

**Comment by Idomo** [comment]
Seems like 0.4.315 finally fixed that issue...
