### ISSUE TITLE
Title Bar

### ISSUE THREAD

**Issue by timea-techgirl** [m4heshd/whatsapp-desktop-dark#5]
Hello,

I have been waiting for this for a year now. I used a dark mode chrome extension and used whatsapp web in chrome. You made my life easier by sharing this awesome tool. Thank you soooo much for that. :)

I changed the title bar colour to dark but the ticks were invisible. Can you tell me a colour code that's good enough to show the ticks as well?

**Comment by m4heshd** [comment]
Hi @timeakesmarky,
Find the `#windows-title-bar` section of your `dark.css` and replace it with

```
#windows-title-bar {
    background-color: var(--bgcol) !important; 
}
#windows-title-minimize:hover, #windows-title-maximize:hover {
    transition: 200ms ease-in-out !important;
    background-color: var(--dark) !important;
}
```

Then reinstall the script. Let me know how it goes.

**Comment by timea-techgirl** [comment]
This is a better colour for accent, the default whatsapp blue ticks colour:
`--accent: #34b7f1;`

I used this:
```
#windows-title-bar {
    background-color: var(--darker) !important; 
}
#windows-title-minimize:hover, #windows-title-maximize:hover {
    transition: 200ms ease-in-out !important;
    background-color: var(--dark) !important; 
}
```

**Comment by timea-techgirl** [comment]
The chat bubble colours could receive more differentiation.
How to change the background colour of conversations to darker?

**Comment by m4heshd** [comment]
That's great. You're free to use any color that eases your eyes.

> The chat bubble colours could receive more differentiation.

Do you mean the profile picture thumbnails from left side pane?

> How to change the background colour of conversations to darker?

It'll be great if you can provide a screenshot of the exact region you're referring to.

**Comment by timea-techgirl** [comment]
These are chat bubbles. Both are black, sender and receiver.
[68747470733a2f2f692e6962622e636f2f666e726b3470342f53637265656e73686f742e706e67](https://user-images.githubusercontent.com/7058205/64189074-3ec21f80-ce91-11e9-89f0-6e0685b6f21c.png)

**Comment by timeakesmarky** [comment]
I want to test a few colours from here:
whatsappbrand<dot>com

**Comment by m4heshd** [comment]
Oh.. you can find the styles by searching for `/* Message bubbles. */` inside the `dark.css`. I thought you were referring to the background with the doodle.

**Comment by timeakesmarky** [comment]
And replace `--darker` and `--msgout` with the colour code?

**Comment by timea-techgirl** [comment]
I just couldn't change the colour of the loading progress bar to whatsapp's blue. Changing these values didn't work.
```
/* Progress. */
progress[value]::-webkit-progress-bar {
    background: var(--darker); }
/* Value. */
progress[value]::-webkit-progress-value {
    background: var(--accent); }
```
![wa](https://user-images.githubusercontent.com/7058205/64191970-471d5900-ce97-11e9-9dc2-fe06c9898aef.jpg)

**Comment by m4heshd** [comment]
Color of the progressbar is inside the `index.html`. It's the only style tag in there.

**Comment by timea-techgirl** [comment]
Thank you! I'm almost done. How can I change this colour?

![68747470733a2f2f692e6962622e636f2f666e726b3470342f53637265656e73686f742e706e67](https://user-images.githubusercontent.com/7058205/64201823-37a90a80-cead-11e9-9c73-62449def59d1.jpg)

**Comment by timea-techgirl** [comment]
And how can I make "typing..." text green. Only this text.

**Comment by m4heshd** [comment]
Hi, sorry for the late response. FYI I've just released a new version with multiple fixes and new implementations. Make sure to start with the new styles. Also it's not possible to change the color of 'typing..' status. Sorry about that.

**Comment by timea-techgirl** [comment]
> Thank you! I'm almost done. How can I change this colour?
> 
> ![68747470733a2f2f692e6962622e636f2f666e726b3470342f53637265656e73686f742e706e67](https://user-images.githubusercontent.com/7058205/64201823-37a90a80-cead-11e9-9c73-62449def59d1.jpg)

Can you answer this?

**Comment by timea-techgirl** [comment]
> Hi, sorry for the late response. FYI I've just release a new version with multiple fixes and new implementations. Make sure to start with the new styles. Also it's not possible to change the color of 'typing..' status. Sorry about that.

How come? it was green in original version, now it's white.

**Comment by m4heshd** [comment]
I'm unable to isolate that element at the moment. Maybe because I'm running 30+ hours without any sleep. Lemme get some rest and take a deeper look into it and let you know. I will update this issue as soon as i find the necessary style elements. Really sorry i couldn't help you at the moment. Keep in touch. 🤘

**Comment by m4heshd** [comment]
Hi, Sorry for being late with the assistance.
Here's the style selector you can use for **typing..** status

```
.gtZer {
	color: var(--accent) !important;
}
```

And here's the current styles for that header block you mentioned. 

```
.I3S-C #main header {
    border: none;
    background-color: var(--dark);
    box-shadow: 0px 0px 3px 0px var(--accent);
}
```

Enjoy!!

**Comment by timea-techgirl** [comment]
@m4heshd I couldn't find this:
```
.gtZer {
	color: var(--accent) !important;
}
```

But I found this and changed its value and it didn't work:
```
/* Typing... */
.vdXUe {
    color: var(--accent) !important; }
```

**Comment by m4heshd** [comment]
just change `.vdXUe` to `.gtZer`.

**Comment by timea-techgirl** [comment]
@m4heshd Now it's blue. I want the same green colour as the unread badges.

**Comment by m4heshd** [comment]
Do you want to change everything that's blue right now to the WhatsApp default green accent? I'm asking this because then i can give you an easier solution.

**Comment by timea-techgirl** [comment]
I want the title bar and header dark. > I did that.
I want only the ticks to be WhatsApp blue.
I want everything else green. > I did this by changing the `--accent` colour.

**Comment by m4heshd** [comment]
That's exactly what i was gonna tell you. Just change the variable values. That's the same reason why i categorized everything in the palette into CSS variables.

**Comment by timea-techgirl** [comment]
But what about the blue ticks? How to change that?
I just want to change the colour of blue ticks (after a message was read)
and I want to change the blue bottom bar colour here:
![Untitled](https://user-images.githubusercontent.com/7058205/64387529-e8eca380-d059-11e9-9bc9-3e0f5550309b.jpg)

That's it. Then my modifications will be complete.

**Comment by m4heshd** [comment]
For blue ticks you can use
```
span[data-icon="msg-dblcheck-ack"] svg path {
    fill: var(--accent) !important;
    opacity: 1 !important;
}
```
And the bottom border is
```
.app .I3S-C .C7QbQ:after {
    border-top-color: var(--accent);
}
```

**Comment by timea-techgirl** [comment]
Thank you! Just need one more thing, chat background colour. I couldn't find it. :)

**Comment by m4heshd** [comment]
Background color is the following selector. But remember it can be user-set.
```
.app .I3S-C ._3siyV {
    background-color: var(--dark);
}
```
And the doodle part in default bg is inverted like this..
```
.app ._1wm9T {
    filter: invert(100%) opacity(0.45) !important;
}
```

**Comment by timea-techgirl** [comment]
Fully dark theme:
[win32.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/3591331/win32.zip)

"+Add blocked contact" is grey.

**Comment by m4heshd** [comment]
Good work. Can you open a new issue with a screenshot for the **"Add blocked contact"** part so it can be fixed in the next release?

**Comment by timea-techgirl** [comment]
Of course :)

**Comment by m4heshd** [comment]
Hi, Just wanted to let you know that latest source contains a feature to customize the accent color. Added in e66673757f27e0863067563e7de5c2d163a008c3. You can clone the repo and do some testing for bugs or improvements.

**Comment by timea-techgirl** [comment]
How to change the unread icon badge color? It was green in the previous version which I prefer. Now it turns to the accent color.

A suggestion is, you can keep the official whatsapp colours such as - `#2CBDA5` for title bar and loading progress bar and whatsapp's blue checkmarks - `#34B7F1` and "typing..." and badges must be 
`#09D261`. These can be the default settings. It's too fragmented right now.

I have to change these back to the default whatsapp colours for every version. Other colours such as ticks and typing mustn't change, just the light areas must change to dark. That is my opinion. Hope it can be done. :)

**Comment by m4heshd** [comment]
I'm sorry but i have to keep it the way majority prefers. That's why I have given as much flexibility as i can for users to edit the styling the way they wish. The same reason why i enabled accent color customization in the script too. That's the best i could do at the moment.

**Comment by timea-techgirl** [comment]
Ok, but I personally think official colours mustn't be changed. Users can change these manually if they want. By default, official colours must be used. Now it's the opposite. I have to change because something is not default.

Anyway how to change the unread icon badge color? It was green in the previous version which I prefer. Now it turns to the accent color. I couldn't find it in style.css

**Comment by m4heshd** [comment]
The commit for that change is 09df5c86b8a332a9bd17f47d768a066afc9667f6. You can simply reverse it.

By the way, this was originally set to WhatsApp default accent color like 8 months ago when i was still working on the basics. But the more i complete it, more it started to look unbelievably odd. Not just my opinion. Everybody i showed this to agreed. Then i found this exact color palette. Not gonna lie but i stole these colors from a much more creative person than me. This particular blue is way more blending and easier on the eyes. So that's the history of it. I might darken the title bar on next release though. Still haven't decided.

**Comment by timea-techgirl** [comment]
Oh I was not talking about the title bar, I'm not worried about it but the blue ticks and typing... and unread badges. Green looks awesome on black, checkmarks in official light blue looks awesome too.

Here is my dark theme with default typing and checkmark colours and default green accent bar and official teal progress bar and black title bar:
[WA-Full-Dark.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/3649350/WA-Full-Dark.zip)

When the app asks to enter a custom accent color, say no.
Now you have a pure dark theme with official colours. :)

**Comment by m4heshd** [comment]
I know but title bar seems to be flashing too much color whenever the user opens WhatsApp window. It gets easier over the time but i think it's time to change the title bar. I opened a poll (#38) so i can have better input.

**Comment by timea-techgirl** [comment]
That's true, first time I installed it, I loved the theme but the blue title bar was odd and brighter, I use a big screen
