### ISSUE TITLE
Again the microphone

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#52]
Well, it's fixed but in the chat, not in the part where all the contacts show.

![image](https://user-images.githubusercontent.com/31411531/66173936-58818e80-e618-11e9-9c94-07af003fb614.png)

**Comment by m4heshd** [comment]
Oh that's a sneaky one. This'll be fixed right away. Thanks for reporting @NicolasPL64.

**Comment by m4heshd** [comment]
Fixed in 0869932895eb2de2b2fc838a0d8a39dd2ae79dff.
