### ISSUE TITLE
New Update broke message backgrounds

### ISSUE THREAD

**Issue by yurividal** [m4heshd/whatsapp-desktop-dark#53]
This morning, after whatsapp auto update, i applied the mod and have this:

![image](https://user-images.githubusercontent.com/8555749/66205278-ea36dd80-e6a4-11e9-87da-9e6dbba00e4e.png)

**Comment by m4heshd** [comment]
Hi @yurividal,
This is a duplicate of issue #47. You can find all the updates and information there.
