### ISSUE TITLE
Style bug? Windows 10

### ISSUE THREAD

**Issue by OficialneMON** [m4heshd/whatsapp-desktop-dark#56]
![image](https://user-images.githubusercontent.com/20894181/66221860-dcca2500-e69d-11e9-898a-1e2472c5a510.png)

**Comment by mcsomenzari** [comment]
Same with me... I think it was after some Office or Windows update ...

**Comment by m4heshd** [comment]
Hi, This is a duplicate of issue #47 and closing this since the release with fix is out.
