### ISSUE TITLE
Maybe adding custom Image background

### ISSUE THREAD

**Issue by Lauriichan** [m4heshd/whatsapp-desktop-dark#59]
If it is possible could you try to add custom image background support?
I know that this isn't easy and maybe not possible but if it is could you maybe try to implement that? (if you didn't tried yet)

**Comment by m4heshd** [comment]
Do you mean a background image for the chat area?

**Comment by Lauriichan** [comment]
yes that's exactly what i mean

**Comment by m4heshd** [comment]
I'm sorry but even though this is possible, it's not very efficient the way we have to achieve this. So this feature won't be implemented. Thank you for the suggestion.
