### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Gusher** [m4heshd/whatsapp-desktop-dark#61]
Is there a way to change font size? Its a bit small on my end and wish to increase...

**Comment by m4heshd** [comment]
Try **`Ctrl + =`** on your keyboard.

**Comment by Gusher** [comment]
Hello, so pressing ctrl and =   ...didn't for me..am on win 10 pro 64bit

**Comment by m4heshd** [comment]
Closing this since this functionality is already available.
