### ISSUE TITLE
Latest build (v0.3.4941) not working in Mac with just a click

### ISSUE THREAD

**Issue by AzrizHaziq** [m4heshd/whatsapp-desktop-dark#63]
### Step to reproduce:
1) Download WADark-0.3.4941-macOS.zip
2) Open Whatsapp desktop
3) Click WADark
4) Error output ![image](https://user-images.githubusercontent.com/9023187/66264900-a0cec580-e83f-11e9-93ea-f5a48bf41f14.png)

### Solution
I have to type sudo `$ sudo /Applications/test/WADark-mac/WADark`

![image](https://user-images.githubusercontent.com/9023187/66264942-54d05080-e840-11e9-9ccc-15e31d7eacd1.png)

**Comment by m4heshd** [comment]
You probably have installed WhatsApp from App store which isn't recommended. But thankfully since a5b3877966f01850d7e0be9b7cb868e8cf5e6f39, you can use `sudo`. Closing the issue.
