### ISSUE TITLE
Unable to launch WADark.exe since update v0.3.4941

### ISSUE THREAD

**Issue by purplpasta** [m4heshd/whatsapp-desktop-dark#64]
I just recently got WA Desktop Dark, however the newest update is not working. If I run WADark.exe  it opens for around a second and then closes itself. The old version works fine and asks me if I want to update... The New version shows me this screen (Image attached) for a second before it closes. Any Idea what I can do? Or else, how do I exit dark mode, because the old version is pretty painfull to look at in the newest version of WhatsApp Desktop...
![wadark error](https://user-images.githubusercontent.com/56203839/66272279-da1b2b80-e867-11e9-81cb-7242e0781ee9.png)

**Comment by m4heshd** [comment]
Hi @OwO-tism,
This is really weird. I wanna see where the issue originates. Can you try to run WADark.exe from Windows powershell? Open up a powershell windows in that location and run `.\WADark.exe`. Post a screenshot of the complete error log. 
Also you can just simply rerun the script to uninstall dark mode.

**Comment by purplpasta** [comment]
The Error fixed itself by moving it to a different folder on my PC... Somehow it could not load in the AppData...? I moved it to another folder since I never used the powershell before and could not figure out how to run it in the previous location and suddenly it worked... I have no idea what just happened but I wont complain ¯\_(ツ)_/¯

**Comment by m4heshd** [comment]
Haha glad it's finally fixed. I'm guessing it was in a restricted location by the platform. Closing the issue but keeping the `unidentified` label since we actually didn't manage to debug the issue.
