### ISSUE TITLE
error installing because of special characters in user name - Windows

### ISSUE THREAD

**Issue by nickmz98** [m4heshd/whatsapp-desktop-dark#65]
I had a problem installing this mod because of the pressence of special characters in my username, Nicolás. I don´t have any experience programming, but I can try and follow some instructions for another method of installation, if there is any. Thanks in advance.

**Comment by m4heshd** [comment]
Hi @nickmz98,
Sorry for the late response. This issue has been already discussed and solved in #29. You can walk through the conversation and ask for help there if needed. Closing this issue.
