### ISSUE TITLE
Chat bubbles from sender don't display correctly

### ISSUE THREAD

**Issue by RuggeDX** [m4heshd/whatsapp-desktop-dark#68]
![Aantekening 2019-10-10 123209](https://user-images.githubusercontent.com/42695100/66561569-01b90f00-eb5a-11e9-9ddb-442c996a7df3.jpg)

A new WhatsApp Desktop update is most likely the culprit here. 
However, I was not prompted to update.

**Comment by elvinon** [comment]
I have the same problem too :(

**Comment by m4heshd** [comment]
Hi @RuggeDX, This issue is confirmed and it seems to be a minor release that just targeted Windows. I'm working on a fix for this which will be available on next release.

**Comment by ahanniga** [comment]
I can confirm it affects Mac too. Thanks Mahesh.

**Comment by tabasko78** [comment]
Hi Guys,
Same for me :(

**Comment by m4heshd** [comment]
Closing this since it has been fixed in the latest release.
