### ISSUE TITLE
Message Info Headers still in White w/Lt Gray Text

### ISSUE THREAD

**Issue by Ktklein72** [m4heshd/whatsapp-desktop-dark#7]
If after sending a message you mouse over the upper right corner of the post and press the down arrow and choose Message Info, the column opens on the right and the Read By, Remaining, Delivered To and Remaining are all in White with Lt. Gray text.  Will attempt to send a screen shot.
![Capture](https://user-images.githubusercontent.com/5505779/64199302-04885c00-ce58-11e9-8f1b-078e35cfb9ed.PNG)

**Comment by m4heshd** [comment]
Hi @Ktklein72,

I've also noticed this a few days ago and this'll be fixed in the next version which is about to be released. Keep in touch. Thank you for reporting.

**Comment by Ktklein72** [comment]
Thanks!  👍

**Comment by m4heshd** [comment]
Closing this issue since It's been fixed on c7c65ff266e505f8f06829aa3315c24635ade255. Enjoy..
