### ISSUE TITLE
Apparently a new version was released so my dark mode restarted

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#70]
F

Now I have 2 folders again xD
![image](https://user-images.githubusercontent.com/31411531/66609667-40ad8b80-eb7f-11e9-9b8d-04d279301c52.png)

**Comment by NicolasPL64** [comment]
![image](https://user-images.githubusercontent.com/31411531/66701769-b02d9300-ecc5-11e9-8042-9495cd1d4067.png)
yep, it's broken

**Comment by m4heshd** [comment]
Hi @NicolasPL64, You've got nothing to worry about those directories and I'm closing this issue since It's already being tracked in #68.
