### ISSUE TITLE
macOS 10.15 Permission denied

### ISSUE THREAD

**Issue by bowenchin** [m4heshd/whatsapp-desktop-dark#71]
Tried running the WADark on macOS 10.15 Catalina and got "Permission Denied" in Terminal.

**Comment by bowenchin** [comment]
<img width="571" alt="Screenshot 2019-10-11 at 10 45 02 AM" src="https://user-images.githubusercontent.com/12101069/66620767-4b663000-ec14-11e9-9a13-25d67d8cd613.png">

**Comment by bowenchin** [comment]
I found the issue, it has to do with the new permissions system in Catalina that requires you to give access to run the script in the Security section of System Preference and changing chmod of the WADark file to 755.

**Comment by m4heshd** [comment]
Hi @bowenchin, Sorry for the late response. Glad you were able to fix the issue. Closing this.
