### ISSUE TITLE
macOS - Hovering over deleting a member x in new group creation is not dark

### ISSUE THREAD

**Issue by glekner** [m4heshd/whatsapp-desktop-dark#72]
<img width="380" alt="Screen Shot 2019-10-13 at 20 09 17" src="https://user-images.githubusercontent.com/24938324/66719215-8a071080-edf5-11e9-9383-ccc8ba7dd4d1.png">

**Comment by m4heshd** [comment]
Hi @glekner, I'll take a look at the PR and merge as soon as i have some time on my hands.
