### ISSUE TITLE
Strange message bars

### ISSUE THREAD

**Issue by Lauriichan** [m4heshd/whatsapp-desktop-dark#75]
There are some strange bars in the chat on the line of the senders messages
they just appeared after updating to the newest version of Whatsapp Dark, in the normal Whatsapp they don't seem to appear
![Unbeaanannt](https://user-images.githubusercontent.com/41839265/66854151-10039280-ef81-11e9-85c6-c4980d71300d.PNG)

**Comment by m4heshd** [comment]
Hi @PlayUniverse, This issue is already being tracked in #68. Feel free to add any info there.
