### ISSUE TITLE
Having this error while installing. Reinstalled the desktop app also. 

### ISSUE THREAD

**Issue by arslanejaz33** [m4heshd/whatsapp-desktop-dark#8]
![Annotation 2019-09-04 104210](https://user-images.githubusercontent.com/21056479/64228668-ecb8e280-cf00-11e9-8ba6-026024a74df1.png)

**Comment by m4heshd** [comment]
Hi @arslanejaz33,

This is an issue related to Windows. You can find some information [here ](https://support.microsoft.com/en-us/help/2664203/invalid-xml-content-error-message-when-you-run-a-wmic-command-in-windo) and on https://github.com/RafalWilinski/express-status-monitor/issues/49

Did you have WhatsApp desktop running before you start the installer?

**Comment by arslanejaz33** [comment]
I restarted my computer and the issue was fixed. Working Perfectly Thank You

**Comment by m4heshd** [comment]
You're very welcome and glad it was resolved.
