### ISSUE TITLE
Theme resets on every restart - MacOS Catalina Issue

### ISSUE THREAD

**Issue by TheMorgz** [m4heshd/whatsapp-desktop-dark#80]
I install the theme. Restart my Mac, and the theme settings do not persist after the reboot of the machine. If I try to re-install the theme after it resets, then it messes the theme up(Grey patches around the message blocks) with inconsistent styling.

**Comment by HillTravis** [comment]
Related to #77

**Comment by m4heshd** [comment]
Closing this since it's a duplicate of #77 and has been fixed in the latest release.
