### ISSUE TITLE
Can't run on Catalina

### ISSUE THREAD

**Issue by thefunkyjoint** [m4heshd/whatsapp-desktop-dark#82]
I followed the instructions but when i click on WADark file, it simply opens a window with a lot of code inside, instead of run something .

Please see the image attached on 

https://ibb.co/16ykzfS

**Comment by Manas73** [comment]
Hey,
You'll have to **open the terminal at the folder containing the WADark file** (right click the folder > Services > New Terminal at Folder) and run the follwing command:
`sudo ./WADark`

**Ensure that your Whatsapp Application is open before following the steps mentioned above.**
PS: I am currently running MacOS Catalina 10.15 and Whatsapp version 0.3.5149 and can confirm it works. However you might get and issue like #77 which even I am facing at the moment and haven't found any solution.

**Comment by jkas777** [comment]
Not working :(

> Hey,
> You'll have to **open the terminal at the folder containing the WADark file** (right click the folder > Services > New Terminal at Folder) and run the follwing command:
> `sudo ./WADark`

(catalina) Not working... 
"Command not found"
<img width="511" alt="Screenshot at Oct 26 12-17-24" src="https://user-images.githubusercontent.com/56317335/67617333-d0437300-f7ea-11e9-8f01-b6c355c9f310.png">

**Comment by jkas777** [comment]
Find this and it's work!

>>> there were a few extra steps not mentioned in the instructions. In order to run the file, open your Terminal, then run cd ~/Downloads/WADark-mac && chmod a+x WADark && ./WADark. You may also need to allow it through your security settings (first try to run it and if it gets blocked, go to the Apple menu > System Preferences > Security & Privacy > Open Anyway).

**Comment by m4heshd** [comment]
Closing this since it's solved..
