### ISSUE TITLE
Theming: Citation background color and link preview background color

### ISSUE THREAD

**Issue by Goldsucher** [m4heshd/whatsapp-desktop-dark#83]
Hi,
2 short questings:
Are there (unique) parameters in the overright.json for the citation background color and the link preview background color? Couldn't figure it out by myself.

<img width="561" alt="screenshot1" src="https://user-images.githubusercontent.com/7906131/67477426-54b2bc00-f65a-11e9-970a-8438c6319f67.png">
<img width="705" alt="screenshot2" src="https://user-images.githubusercontent.com/7906131/67477427-54b2bc00-f65a-11e9-91be-5589b58ae444.png">

**Comment by m4heshd** [comment]
Hi @Goldsucher,
There aren't any unique variables designated for these particular sections. 1st one is using the `--dark` CSS variable and the second one is using the `--darker` CSS variable with a alpha-black layer on top of it. Closing this since it's not an issue.
