### ISSUE TITLE
Its not an issue just an request.

### ISSUE THREAD

**Issue by ghost** [m4heshd/whatsapp-desktop-dark#86]
Hello it's me again :)
I just wanted to ask if I can use your theme files for my injector I want to publish because I'm too lazy to make my own.

I just want to publish a new injector for WA Desktop Darkmode just for the people who had the same problem as I did and can't use yours.

Of course I give you credits etc. I already have because the Injector comes from you (see appendix).

I hope for your understanding :)
~ Sören

![image](https://user-images.githubusercontent.com/33805688/67782625-55d45680-fa69-11e9-9e6f-1f0acfd88a2e.png)

**Comment by m4heshd** [comment]
Hi @CrashedLife,
Sorry for the very late response. Of course you can. Just make sure to include the licence from this project too so you're legally all set. But i do highly suggest you to look through the source of this project and try to fix the issue right here so people can find it in one place.

**Comment by Moulick** [comment]
@CrashedLife Yep, I agree with @m4heshd here. The better way would be to fix things here and make this repo work for all people...

**Comment by ghost** [comment]
Yeah thank you m4heshd 
I´ll search a fix for it.

I´ll be keep you up to date if I find something. :)

**Comment by ghost** [comment]
Btw I will close this now.

I´ve reseted my PC for some reasons and It should be working now I think I´ll test it in a few minutes.
One of the points that I figured out was you need to change UTF-8 to a Encoding languages that allows other letters like ä, ö, ü, ß...

~ Sören :)
