### ISSUE TITLE
Very unresponsive

### ISSUE THREAD

**Issue by keyute** [m4heshd/whatsapp-desktop-dark#9]
Whatsapp is incredibly unresponsive on macos latest version of whatsapp

The application would not respond at times when opening it from background, and interaction (ie clicking buttons typing) triggers it as well

**Comment by m4heshd** [comment]
Hi @keyute,

Can you tell me your WhatsApp version? I just checked on mine and it works fine.

**Comment by keyute** [comment]
> Hi @keyute,
> 
> Can you tell me your WhatsApp version? I just checked on mine and it works fine.

0.3.4479

**Comment by m4heshd** [comment]
That's really unusual because I'm unable to reproduce this issue. Are you sure you're using the latest version of the dark mode too? Because i released the latest version just a few hours back.

**Comment by keyute** [comment]
> That's really unusual because I'm unable to reproduce this issue. Are you sure you're using the latest version of the dark mode too? Because i released the latest version just a few hours back.

yes i am. i uninstalled the app store version of whatsapp and installed the latest from the website, extracted ur latest zip and opened the file in root folder. it freezes. going back to the app store version seemed to work fine but that means i can't use your theme

**Comment by keyute** [comment]
> > That's really unusual because I'm unable to reproduce this issue. Are you sure you're using the latest version of the dark mode too? Because i released the latest version just a few hours back.
> 
> yes i am. i uninstalled the app store version of whatsapp and installed the latest from the website, extracted ur latest zip and opened the file in root folder. it freezes. going back to the app store version seemed to work fine but that means i can't use your theme

try force quitting the app (command + Q) and opening the app again. the issue started then

**Comment by m4heshd** [comment]
Lemme take some time and look into this. Are you on macOS 10.14.6?

**Comment by keyute** [comment]
> Lemme take some time and look into this. Are you on macOS 10.14.6?

yep

**Comment by m4heshd** [comment]
I have checked every possible scenario and I'm sorry i can't seem to reproduce this issue. I'm on the same macOS version as you and all the other versions match with yours too. I even got some other users to check and nobody complained about any performance issue. Any chance you can try on another mac?

**Comment by keyute** [comment]
As it appears that the lag is not isolated to Whatsapp, I've wiped my macbook and it now works like a charm

**Comment by m4heshd** [comment]
That's great to hear. Hope you're enjoying it. Also the source contains some great new features if you like to check them out.
