### ISSUE TITLE
It works but I received a few errors when running the script

### ISSUE THREAD

**Issue by jonas4climate** [m4heshd/whatsapp-desktop-dark#90]
I executed it using `npm install` and `node` on MacOS Catalina 10.15

<img width="1084" alt="Screenshot 2019-10-31 at 2 37 14 pm" src="https://user-images.githubusercontent.com/44198728/67956743-7f69bb00-fbec-11e9-8616-fac88e49a8b6.png">

My Whatsapp has Darkmode and seems to be all fine and `node .` performed errorless.
Just a heads up if this was an issue that would help you.

Below the npm error log file
[2019-10-31T14_35_01_691Z-debug.log](https://github.com/m4heshd/whatsapp-desktop-dark/files/3794332/2019-10-31T14_35_01_691Z-debug.log)

**Comment by m4heshd** [comment]
The postinstall script is only valid for Windows and you can simply ignore it. Closing the issue.
