### ISSUE TITLE
Unable to run WADark script in macOS

### ISSUE THREAD

**Issue by justinlee979** [m4heshd/whatsapp-desktop-dark#91]
![image](https://user-images.githubusercontent.com/57401849/68212617-d5879580-0014-11ea-941d-cc23c055125a.png)

Every time I double click WADark, it just opens it in TextEdit. I am not able to run it in Script Editor

**Comment by UnderEu** [comment]
Follow these steps:
- Open the WA app;
- Open Terminal;
- Type: `chmod +x` [drag the WADark file into the Terminal window] [Hit Return/Enter];

then

- [drag the WADark file into the Terminal window] [Hit Return/Enter];
- Follow the instructions on screen;
- Bless your eyes.

@m4heshd Add those in a README.txt among macOS bundle.

**Comment by justinlee979** [comment]
After dragging the WADark file in and hitting enter, it says 'permission denied'

**Comment by justinlee979** [comment]
Managed to get it to work after following your steps. Thank you!

**Comment by m4heshd** [comment]
Closing this since the issue is solved.
