### ISSUE TITLE
Weird bars showing on own messages

### ISSUE THREAD

**Issue by TryhardOne** [m4heshd/whatsapp-desktop-dark#92]
Hello, I installed your theme today, and modified it to my own version. However there was one thing that bothered me and I couldnt find out how to fix it.
There are bars showing, on every of my own messages, not on other persons though.
![image](https://user-images.githubusercontent.com/44778412/68224893-c510f400-ffef-11e9-9e13-9a204d80f35c.png)

**Comment by benthuss** [comment]
I am having this same exact problem as well! 

Running Mac OSX Mojave 10.14.6 and Whats App version 0.3.5374

**Comment by benthuss** [comment]
> Hello, I installed your theme today, and modified it to my own version. However there was one thing that bothered me and I couldnt find out how to fix it.
> There are bars showing, on every of my own messages, not on other persons though.
> ![image](https://user-images.githubusercontent.com/44778412/68224893-c510f400-ffef-11e9-9e13-9a204d80f35c.png)

Hey there, I found a fix for this inside another issue thread, FYI 

https://github.com/m4heshd/whatsapp-desktop-dark/issues/77#issuecomment-547098408

**Comment by TryhardOne** [comment]
> > Hello, I installed your theme today, and modified it to my own version. However there was one thing that bothered me and I couldnt find out how to fix it.
> > There are bars showing, on every of my own messages, not on other persons though.
> > ![image](https://user-images.githubusercontent.com/44778412/68224893-c510f400-ffef-11e9-9e13-9a204d80f35c.png)
> 
> Hey there, I found a fix for this inside another issue thread, FYI
> 
> [#77 (comment)](https://github.com/m4heshd/whatsapp-desktop-dark/issues/77#issuecomment-547098408)

NICE! that fixed it, thanks!
