### ISSUE TITLE
White message while "contact added you to a group"

### ISSUE THREAD

**Issue by UnderEu** [m4heshd/whatsapp-desktop-dark#93]
I was just added to a new group and the message who says "_Contact XYZ added you_" still appears in white, as shown in the screenshot below.

WhatsApp Desktop v0.3.4941 - macOS

Screenshot: ![IMG_60B5DE15028B-1](https://user-images.githubusercontent.com/16519758/68263327-80ec1680-0024-11ea-9351-2ad78b3fbc83.jpeg)
*Content blurred due to privacy concerns.

**Comment by UnderEu** [comment]
Looks like WA 0.3.9309 somehow fixed this issue.

Screenshot: ![Screen Shot 2020-01-04 at 15 57 34](https://user-images.githubusercontent.com/16519758/71770558-bf129300-2f0c-11ea-811a-64b44a547912.png)

**Comment by m4heshd** [comment]
Closing this since the issue has been fixed.
